/**
 * ════════════════════════════════════════════════════════════════
 * 📏 Localized Unit Names
 * ════════════════════════════════════════════════════════════════
 * Translates measurement unit codes/names to the user's display language.
 * Supports: ar, en, ru, uk, tr, de, it, ro, pl
 */

const UNIT_MAP: Record<string, Record<string, string>> = {
  // Meter
  meter:  { ar: 'متر', en: 'm', ru: 'м', uk: 'м', tr: 'm', de: 'm', it: 'm', ro: 'm', pl: 'm' },
  'متر': { ar: 'متر', en: 'm', ru: 'м', uk: 'м', tr: 'm', de: 'm', it: 'm', ro: 'm', pl: 'm' },
  m:      { ar: 'متر', en: 'm', ru: 'м', uk: 'м', tr: 'm', de: 'm', it: 'm', ro: 'm', pl: 'm' },

  // Kilogram
  kg:     { ar: 'كغ', en: 'kg', ru: 'кг', uk: 'кг', tr: 'kg', de: 'kg', it: 'kg', ro: 'kg', pl: 'kg' },
  kilogram: { ar: 'كغ', en: 'kg', ru: 'кг', uk: 'кг', tr: 'kg', de: 'kg', it: 'kg', ro: 'kg', pl: 'kg' },
  'كغ':   { ar: 'كغ', en: 'kg', ru: 'кг', uk: 'кг', tr: 'kg', de: 'kg', it: 'kg', ro: 'kg', pl: 'kg' },
  'كيلو': { ar: 'كيلو', en: 'kg', ru: 'кг', uk: 'кг', tr: 'kg', de: 'kg', it: 'kg', ro: 'kg', pl: 'kg' },

  // Piece
  piece:  { ar: 'قطعة', en: 'pcs', ru: 'шт', uk: 'шт', tr: 'adet', de: 'Stk', it: 'pz', ro: 'buc', pl: 'szt' },
  pcs:    { ar: 'قطعة', en: 'pcs', ru: 'шт', uk: 'шт', tr: 'adet', de: 'Stk', it: 'pz', ro: 'buc', pl: 'szt' },
  'قطعة': { ar: 'قطعة', en: 'pcs', ru: 'шт', uk: 'шт', tr: 'adet', de: 'Stk', it: 'pz', ro: 'buc', pl: 'szt' },

  // Roll
  roll:   { ar: 'رول', en: 'roll', ru: 'рулон', uk: 'рулон', tr: 'rulo', de: 'Rolle', it: 'rotolo', ro: 'rolă', pl: 'rolka' },
  'رول':  { ar: 'رول', en: 'roll', ru: 'рулон', uk: 'рулон', tr: 'rulo', de: 'Rolle', it: 'rotolo', ro: 'rolă', pl: 'rolka' },

  // Yard
  yard:   { ar: 'يارد', en: 'yd', ru: 'ярд', uk: 'ярд', tr: 'yarda', de: 'Yard', it: 'iarda', ro: 'iard', pl: 'jard' },
  'يارد': { ar: 'يارد', en: 'yd', ru: 'ярд', uk: 'ярд', tr: 'yarda', de: 'Yard', it: 'iarda', ro: 'iard', pl: 'jard' },

  // Liter
  liter:  { ar: 'لتر', en: 'L', ru: 'л', uk: 'л', tr: 'lt', de: 'L', it: 'L', ro: 'L', pl: 'L' },
  'لتر':  { ar: 'لتر', en: 'L', ru: 'л', uk: 'л', tr: 'lt', de: 'L', it: 'L', ro: 'L', pl: 'L' },

  // Box
  box:    { ar: 'كرتونة', en: 'box', ru: 'коробка', uk: 'коробка', tr: 'kutu', de: 'Karton', it: 'scatola', ro: 'cutie', pl: 'pudło' },
  'كرتونة': { ar: 'كرتونة', en: 'box', ru: 'коробка', uk: 'коробка', tr: 'kutu', de: 'Karton', it: 'scatola', ro: 'cutie', pl: 'pudło' },
};

/**
 * Get the localized unit label for the given unit code/name and language.
 * Falls back to the original unit value if no translation is found.
 */
export function getLocalizedUnit(unit: string | null | undefined, language: string): string {
  if (!unit) return '';
  const normalized = unit.trim().toLowerCase();
  const entry = UNIT_MAP[unit] || UNIT_MAP[normalized];
  if (!entry) return unit; // fallback: return as-is
  return entry[language] || entry.en || unit;
}

/**
 * Common warehouse labels translated to all 9 languages.
 */
const LABELS: Record<string, Record<string, string>> = {
  loose:       { ar: 'سائب', en: 'loose', ru: 'россыпь', uk: 'розсипом', tr: 'dökme', de: 'lose', it: 'sfuso', ro: 'vrac', pl: 'luzem' },
  roll_short:  { ar: 'رول', en: 'R', ru: 'рул', uk: 'рул', tr: 'R', de: 'R', it: 'R', ro: 'R', pl: 'R' },
  rolls:       { ar: 'رول', en: 'Rolls', ru: 'Рулоны', uk: 'Рулони', tr: 'Rulo', de: 'Rollen', it: 'Rotoli', ro: 'Role', pl: 'Rolki' },
  total_qty:   { ar: 'إجمالي الكمية', en: 'Total Quantity', ru: 'Общее количество', uk: 'Загальна кількість', tr: 'Toplam Miktar', de: 'Gesamtmenge', it: 'Quantità totale', ro: 'Cantitate totală', pl: 'Ilość całkowita' },
  rolls_count: { ar: 'عدد الرولونات', en: 'Rolls Count', ru: 'Количество рулонов', uk: 'Кількість рулонів', tr: 'Rulo Sayısı', de: 'Rollenanzahl', it: 'Conteggio rotoli', ro: 'Număr role', pl: 'Liczba rolek' },
  loose_stock: { ar: 'الكمية السائبة', en: 'Loose Stock', ru: 'Россыпной запас', uk: 'Розсипний запас', tr: 'Dökme Stok', de: 'Loser Bestand', it: 'Stock sfuso', ro: 'Stoc vrac', pl: 'Stan luzem' },
  stock_info:  { ar: 'معلومات المخزون', en: 'Stock Information', ru: 'Информация о запасах', uk: 'Інформація про запаси', tr: 'Stok Bilgileri', de: 'Bestandsinformationen', it: 'Informazioni scorte', ro: 'Informații stoc', pl: 'Informacje o stanie' },
  description: { ar: 'الوصف', en: 'Description', ru: 'Описание', uk: 'Опис', tr: 'Açıklama', de: 'Beschreibung', it: 'Descrizione', ro: 'Descriere', pl: 'Opis' },
  contents:    { ar: 'المحتويات', en: 'Contents', ru: 'Содержимое', uk: 'Вміст', tr: 'İçerik', de: 'Inhalt', it: 'Contenuti', ro: 'Conținut', pl: 'Zawartość' },
  edit:        { ar: 'تعديل', en: 'Edit', ru: 'Редактировать', uk: 'Редагувати', tr: 'Düzenle', de: 'Bearbeiten', it: 'Modifica', ro: 'Editare', pl: 'Edytuj' },
  edit_group:  { ar: 'تعديل المجموعة', en: 'Edit group', ru: 'Ред. группу', uk: 'Ред. групу', tr: 'Grubu düzenle', de: 'Gruppe bearbeiten', it: 'Modifica gruppo', ro: 'Editare grup', pl: 'Edytuj grupę' },
  add_material:{ ar: 'إضافة مادة', en: 'Add Material', ru: 'Добавить материал', uk: 'Додати матеріал', tr: 'Malzeme Ekle', de: 'Material hinzufügen', it: 'Aggiungi materiale', ro: 'Adaugă material', pl: 'Dodaj materiał' },
  add_child:   { ar: 'إضافة فرعي', en: 'Add Child', ru: 'Добавить дочерний', uk: 'Додати дочірній', tr: 'Alt öğe ekle', de: 'Unterelement', it: 'Aggiungi figlio', ro: 'Adaugă copil', pl: 'Dodaj podrzędny' },
  delete:      { ar: 'حذف', en: 'Delete', ru: 'Удалить', uk: 'Видалити', tr: 'Sil', de: 'Löschen', it: 'Elimina', ro: 'Șterge', pl: 'Usuń' },
  mat_details: { ar: 'تفاصيل المادة', en: 'Material Details', ru: 'Детали материала', uk: 'Деталі матеріалу', tr: 'Malzeme Detayları', de: 'Materialdetails', it: 'Dettagli materiale', ro: 'Detalii material', pl: 'Szczegóły materiału' },
  edit_item:   { ar: 'تعديل البطاقة', en: 'Edit Item', ru: 'Редактировать', uk: 'Редагувати', tr: 'Öğeyi Düzenle', de: 'Bearbeiten', it: 'Modifica elemento', ro: 'Editare element', pl: 'Edytuj element' },
  empty_folder:{ ar: 'هذا المجلد فارغ', en: 'This folder is empty', ru: 'Папка пуста', uk: 'Тека порожня', tr: 'Klasör boş', de: 'Ordner ist leer', it: 'Cartella vuota', ro: 'Dosar gol', pl: 'Folder jest pusty' },
  no_data:     { ar: 'لا توجد بيانات', en: 'No data available', ru: 'Нет данных', uk: 'Немає даних', tr: 'Veri yok', de: 'Keine Daten', it: 'Nessun dato', ro: 'Fără date', pl: 'Brak danych' },
  ecommerce:   { ar: 'المتجر الإلكتروني', en: 'E-commerce', ru: 'Интернет-магазин', uk: 'Інтернет-магазин', tr: 'E-ticaret', de: 'E-Commerce', it: 'E-commerce', ro: 'E-commerce', pl: 'E-commerce' },
  published:   { ar: 'منشور في المتجر', en: 'Published on Store', ru: 'Опубликовано', uk: 'Опубліковано', tr: 'Mağazada', de: 'Veröffentlicht', it: 'Pubblicato', ro: 'Publicat', pl: 'Opublikowane' },
  not_published:{ ar: 'غير منشور', en: 'Not Published', ru: 'Не опубликовано', uk: 'Не опубліковано', tr: 'Yayınlanmadı', de: 'Nicht veröffentlicht', it: 'Non pubblicato', ro: 'Nepublicat', pl: 'Nieopublikowane' },
  sell_price:  { ar: 'سعر البيع', en: 'Selling Price', ru: 'Цена продажи', uk: 'Ціна продажу', tr: 'Satış Fiyatı', de: 'Verkaufspreis', it: 'Prezzo vendita', ro: 'Preț vânzare', pl: 'Cena sprzedaży' },
  parent:      { ar: 'أم', en: 'Parent', ru: 'Родитель', uk: 'Батьківський', tr: 'Ana', de: 'Überordnung', it: 'Genitore', ro: 'Părinte', pl: 'Nadrzędny' },
  // Stat cards
  total_materials: { ar: 'إجمالي المواد', en: 'Total Materials', ru: 'Всего материалов', uk: 'Всього матеріалів', tr: 'Toplam Malzeme', de: 'Materialien gesamt', it: 'Materiali totali', ro: 'Total materiale', pl: 'Materiały ogółem' },
  active_materials:{ ar: 'المواد النشطة', en: 'Active Materials', ru: 'Активные', uk: 'Активні', tr: 'Aktif Malzeme', de: 'Aktive Materialien', it: 'Materiali attivi', ro: 'Materiale active', pl: 'Aktywne materiały' },
  groups:      { ar: 'المجموعات', en: 'Groups', ru: 'Группы', uk: 'Групи', tr: 'Gruplar', de: 'Gruppen', it: 'Gruppi', ro: 'Grupuri', pl: 'Grupy' },
  total_stock: { ar: 'إجمالي المخزون', en: 'Total Stock', ru: 'Общий запас', uk: 'Загальний запас', tr: 'Toplam Stok', de: 'Gesamtbestand', it: 'Scorte totali', ro: 'Stoc total', pl: 'Całkowity stan' },
  loose_total: { ar: 'المخزون السائب', en: 'Loose Stock', ru: 'Россыпной', uk: 'Розсипний', tr: 'Dökme Stok', de: 'Loser Bestand', it: 'Sfuso', ro: 'Vrac', pl: 'Luzem' },
  add_group:   { ar: 'إضافة مجموعة', en: 'Add Group', ru: 'Добавить группу', uk: 'Додати групу', tr: 'Grup Ekle', de: 'Gruppe hinzufügen', it: 'Aggiungi gruppo', ro: 'Adaugă grup', pl: 'Dodaj grupę' },
  import:      { ar: 'استيراد', en: 'Import', ru: 'Импорт', uk: 'Імпорт', tr: 'İçe Aktar', de: 'Importieren', it: 'Importa', ro: 'Import', pl: 'Import' },
  hide_zero:   { ar: 'إخفاء الأرصدة الصفرية', en: 'Hide zero stock', ru: 'Скрыть нулевой запас', uk: 'Сховати нульовий запас', tr: 'Sıfır stoku gizle', de: 'Nullbestand ausblenden', it: 'Nascondi stock zero', ro: 'Ascunde stoc zero', pl: 'Ukryj zerowy stan' },
  low_stock:   { ar: 'نواقص الحد الأدنى فقط', en: 'Low stock only', ru: 'Только низкий запас', uk: 'Тільки низький запас', tr: 'Sadece düşük stok', de: 'Nur niedriger Bestand', it: 'Solo scorte basse', ro: 'Doar stoc scăzut', pl: 'Tylko niski stan' },
  manage_desc: { ar: 'إدارة المواد والمنتجات في قاعدة البيانات', en: 'Manage materials and products in the database', ru: 'Управление материалами и товарами в базе данных', uk: 'Управління матеріалами та товарами в базі даних', tr: 'Veritabanında malzeme ve ürün yönetimi', de: 'Materialien und Produkte in der Datenbank verwalten', it: 'Gestione materiali e prodotti nel database', ro: 'Gestionarea materialelor și produselor în baza de date', pl: 'Zarządzanie materiałami i produktami w bazie danych' },
  // Tree grouping modes
  by_design:      { ar: 'حسب التصميم', en: 'By Design', ru: 'По дизайну', uk: 'За дизайном', tr: 'Tasarıma Göre', de: 'Nach Design', it: 'Per design', ro: 'După design', pl: 'Wg wzoru' },
  by_design_desc: { ar: 'متغيرات اللون داخل التصميم', en: 'Color variants inside design', ru: 'Цветовые варианты внутри дизайна', uk: 'Кольорові варіанти в дизайні', tr: 'Tasarım içinde renk varyantları', de: 'Farbvarianten im Design', it: 'Varianti colore nel design', ro: 'Variante de culoare în design', pl: 'Warianty kolorów w wzorze' },
  by_color:       { ar: 'حسب اللون', en: 'By Color', ru: 'По цвету', uk: 'За кольором', tr: 'Renge Göre', de: 'Nach Farbe', it: 'Per colore', ro: 'După culoare', pl: 'Wg koloru' },
  by_color_desc:  { ar: 'متغيرات التصميم داخل اللون', en: 'Design variants inside color', ru: 'Варианты дизайна внутри цвета', uk: 'Варіанти дизайну в кольорі', tr: 'Renk içinde tasarım varyantları', de: 'Designvarianten in Farbe', it: 'Varianti design nel colore', ro: 'Variante de design în culoare', pl: 'Warianty wzorów w kolorze' },
  by_category:      { ar: 'حسب الفئة', en: 'By Category', ru: 'По категории', uk: 'За категорією', tr: 'Kategoriye Göre', de: 'Nach Kategorie', it: 'Per categoria', ro: 'După categorie', pl: 'Wg kategorii' },
  by_category_desc: { ar: 'كل المواد بدون تجميع فرعي', en: 'All materials without sub-grouping', ru: 'Все материалы без подгрупп', uk: 'Всі матеріали без підгруп', tr: 'Alt gruplama olmadan tüm malzemeler', de: 'Alle Materialien ohne Untergruppen', it: 'Tutti i materiali senza sottogruppi', ro: 'Toate materialele fără sub-grupare', pl: 'Wszystkie materiały bez podgrup' },
  flat_view:      { ar: 'عرض مسطح', en: 'Flat View', ru: 'Плоский вид', uk: 'Плоский вигляд', tr: 'Düz Görünüm', de: 'Flache Ansicht', it: 'Vista piatta', ro: 'Vedere plată', pl: 'Widok płaski' },
  flat_view_desc: { ar: 'كل المواد في مستوى واحد', en: 'All materials in one level', ru: 'Все материалы на одном уровне', uk: 'Всі матеріали на одному рівні', tr: 'Tüm malzemeler tek seviyede', de: 'Alle Materialien auf einer Ebene', it: 'Tutti i materiali su un livello', ro: 'Toate materialele pe un nivel', pl: 'Wszystkie materiały na jednym poziomie' },
  inactive:       { ar: 'غير نشط', en: 'Inactive', ru: 'Неактивно', uk: 'Неактивно', tr: 'Pasif', de: 'Inaktiv', it: 'Inattivo', ro: 'Inactiv', pl: 'Nieaktywne' },
  code_label:     { ar: 'الكود', en: 'Code', ru: 'Код', uk: 'Код', tr: 'Kod', de: 'Code', it: 'Codice', ro: 'Cod', pl: 'Kod' },
  name_label:     { ar: 'الاسم', en: 'Name', ru: 'Название', uk: 'Назва', tr: 'Ad', de: 'Name', it: 'Nome', ro: 'Nume', pl: 'Nazwa' },
  category_label: { ar: 'التصنيف', en: 'Category', ru: 'Категория', uk: 'Категорія', tr: 'Kategori', de: 'Kategorie', it: 'Categoria', ro: 'Categorie', pl: 'Kategoria' },
  status_label:   { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum', de: 'Status', it: 'Stato', ro: 'Stare', pl: 'Status' },
  active_label:   { ar: 'نشط', en: 'Active', ru: 'Активно', uk: 'Активно', tr: 'Aktif', de: 'Aktiv', it: 'Attivo', ro: 'Activ', pl: 'Aktywne' },
  group_label:    { ar: 'مجموعة', en: 'Group', ru: 'Группа', uk: 'Група', tr: 'Grup', de: 'Gruppe', it: 'Gruppo', ro: 'Grup', pl: 'Grupa' },
  // Empty state
  no_materials:   { ar: 'لا توجد مواد بعد', en: 'No Materials Yet', ru: 'Материалов пока нет', uk: 'Матеріалів поки немає', tr: 'Henüz malzeme yok', de: 'Noch keine Materialien', it: 'Nessun materiale', ro: 'Niciun material încă', pl: 'Brak materiałów' },
  no_materials_desc: { ar: 'ابدأ بإضافة المواد يدوياً أو استورد بيانات المواد من ملف Excel مع الكميات والأسعار والعملات بضغطة واحدة', en: 'Start by adding materials manually or import your materials data from an Excel file with quantities, prices and currencies in one click', ru: 'Начните с добавления материалов вручную или импортируйте данные из файла Excel с количествами, ценами и валютами в один клик', uk: 'Почніть з додавання матеріалів вручну або імпортуйте дані з файлу Excel з кількістю, цінами та валютами в один клік', tr: 'Malzemeleri manuel ekleyerek başlayın veya Excel dosyasından miktar, fiyat ve para birimi ile tek tıkla içe aktarın', de: 'Fügen Sie Materialien manuell hinzu oder importieren Sie aus einer Excel-Datei', it: 'Inizia aggiungendo materiali o importa da file Excel', ro: 'Începeți adăugând materiale sau importați din Excel', pl: 'Zacznij dodawać materiały lub importuj z pliku Excel' },
  import_excel:   { ar: 'استيراد من Excel', en: 'Import from Excel', ru: 'Импорт из Excel', uk: 'Імпорт з Excel', tr: "Excel'den İçe Aktar", de: 'Aus Excel importieren', it: 'Importa da Excel', ro: 'Import din Excel', pl: 'Import z Excel' },
  create_group:   { ar: 'إنشاء مجموعة', en: 'Create Group', ru: 'Создать группу', uk: 'Створити групу', tr: 'Grup Oluştur', de: 'Gruppe erstellen', it: 'Crea gruppo', ro: 'Creează grup', pl: 'Utwórz grupę' },
  import_hint:    { ar: '💡 يمكنك استيراد المواد مع الكميات الافتتاحية والأسعار والعملة والمستودع — سيتم إنشاء القيد المحاسبي تلقائياً', en: '💡 Import materials with opening quantities, prices, currency and warehouse — accounting entries are created automatically', ru: '💡 Импортируйте материалы с начальными количествами, ценами, валютой и складом — бухгалтерские записи создаются автоматически', uk: '💡 Імпортуйте матеріали з початковими кількостями, цінами, валютою та складом — бухгалтерські записи створюються автоматично', tr: '💡 Malzemeleri açılış miktarları, fiyatlar, para birimi ve depo ile içe aktarın — muhasebe kayıtları otomatik oluşturulur', de: '💡 Importieren Sie Materialien mit Eröffnungsmengen, Preisen, Währung und Lager — Buchungen werden automatisch erstellt', it: '💡 Importa materiali con quantità, prezzi, valuta e magazzino — le registrazioni contabili vengono create automaticamente', ro: '💡 Importați materiale cu cantități, prețuri, monedă și depozit — înregistrările contabile sunt create automat', pl: '💡 Importuj materiały z ilościami, cenami, walutą i magazynem — zapisy księgowe tworzone automatycznie' },
  tree_view:      { ar: 'شجرة', en: 'Tree', ru: 'Дерево', uk: 'Дерево', tr: 'Ağaç', de: 'Baum', it: 'Albero', ro: 'Arbore', pl: 'Drzewo' },
  table_view:     { ar: 'جدول', en: 'Table', ru: 'Таблица', uk: 'Таблиця', tr: 'Tablo', de: 'Tabelle', it: 'Tabella', ro: 'Tabel', pl: 'Tabela' },
  select_item:    { ar: 'اختر عنصراً لعرض التفاصيل', en: 'Select an item to view details', ru: 'Выберите элемент для просмотра', uk: 'Виберіть елемент для перегляду', tr: 'Detayları görüntülemek için bir öğe seçin', de: 'Wählen Sie ein Element aus', it: 'Seleziona un elemento per i dettagli', ro: 'Selectați un element', pl: 'Wybierz element do wyświetlenia' },
  // ═══ Inventory Page ═══
  search:         { ar: 'بحث', en: 'Search', ru: 'Поиск', uk: 'Пошук', tr: 'Arama' },
  warehouse:      { ar: 'المستودع', en: 'Warehouse', ru: 'Склад', uk: 'Склад', tr: 'Depo' },
  all_warehouses: { ar: 'كل المستودعات', en: 'All Warehouses', ru: 'Все склады', uk: 'Усі склади', tr: 'Tüm Depolar' },
  season:         { ar: 'الموسم', en: 'Season', ru: 'Сезон', uk: 'Сезон', tr: 'Sezon' },
  all_seasons:    { ar: 'كل المواسم', en: 'All Seasons', ru: 'Все сезоны', uk: 'Усі сезони', tr: 'Tüm Sezonlar' },
  winter:         { ar: '❄️ شتوي', en: '❄️ Winter', ru: '❄️ Зима', uk: '❄️ Зима', tr: '❄️ Kış' },
  spring:         { ar: '🌸 ربيعي', en: '🌸 Spring', ru: '🌸 Весна', uk: '🌸 Весна', tr: '🌸 İlkbahar' },
  summer:         { ar: '☀️ صيفي', en: '☀️ Summer', ru: '☀️ Лето', uk: '☀️ Літо', tr: '☀️ Yaz' },
  autumn:         { ar: '🍂 خريفي', en: '🍂 Autumn', ru: '🍂 Осень', uk: '🍂 Осінь', tr: '🍂 Sonbahar' },
  currency:       { ar: 'العملة', en: 'Currency', ru: 'Валюта', uk: 'Валюта', tr: 'Para Birimi' },
  status_filter:  { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  all:            { ar: 'الكل', en: 'All', ru: 'Все', uk: 'Усі', tr: 'Tümü' },
  in_stock:       { ar: '🟢 متوفر', en: '🟢 In Stock', ru: '🟢 В наличии', uk: '🟢 В наявності', tr: '🟢 Stokta' },
  low_stock_status: { ar: '🟡 مخزون منخفض', en: '🟡 Low Stock', ru: '🟡 Мало', uk: '🟡 Мало', tr: '🟡 Az Stok' },
  out_of_stock:   { ar: '🔴 نفذ', en: '🔴 Out of Stock', ru: '🔴 Нет', uk: '🔴 Немає', tr: '🔴 Tükendi' },
  color_filter:   { ar: 'اللون', en: 'Color', ru: 'Цвет', uk: 'Колір', tr: 'Renk' },
  all_colors:     { ar: 'كل الألوان', en: 'All Colors', ru: 'Все цвета', uk: 'Усі кольори', tr: 'Tüm Renkler' },
  stock_type:     { ar: 'نوع المخزون', en: 'Stock Type', ru: 'Тип запаса', uk: 'Тип запасу', tr: 'Stok Türü' },
  stock_all:      { ar: '📦 الكل', en: '📦 All', ru: '📦 Все', uk: '📦 Усі', tr: '📦 Tümü' },
  stock_rolls:    { ar: '🎯 رولونات فقط', en: '🎯 Rolls Only', ru: '🎯 Только рулоны', uk: '🎯 Тільки рулони', tr: '🎯 Sadece Rulolar' },
  stock_loose:    { ar: '📏 سائب فقط', en: '📏 Loose Only', ru: '📏 Только россыпь', uk: '📏 Тільки розсип', tr: '📏 Sadece Dökme' },
  stock_mixed:    { ar: '🔀 مختلط', en: '🔀 Mixed', ru: '🔀 Смешанный', uk: '🔀 Змішаний', tr: '🔀 Karışık' },
  clear:          { ar: 'مسح الكل', en: 'Clear', ru: 'Очистить', uk: 'Очистити', tr: 'Temizle' },
  transfer:       { ar: 'مناقلة', en: 'Transfer', ru: 'Перемещение', uk: 'Переміщення', tr: 'Transfer' },
  columns:        { ar: 'الأعمدة', en: 'Columns', ru: 'Столбцы', uk: 'Стовпці', tr: 'Sütunlar' },
  show_hide_cols: { ar: 'إظهار / إخفاء الأعمدة', en: 'Show / Hide Columns', ru: 'Показать / Скрыть столбцы', uk: 'Показати / Сховати стовпці', tr: 'Sütunları Göster / Gizle' },
  rolls_qty:          { ar: 'رولون', en: 'rolls', ru: 'рулонов', uk: 'рулонів', tr: 'rulo' },
  items:          { ar: 'عنصر', en: 'items', ru: 'позиций', uk: 'позицій', tr: 'öğe' },
  total:          { ar: 'الإجمالي', en: 'Total', ru: 'Итого', uk: 'Всього', tr: 'Toplam' },
  // Inventory column labels
  col_colors:     { ar: 'الألوان', en: 'Colors', ru: 'Цвета', uk: 'Кольори', tr: 'Renkler' },
  col_rolls:      { ar: 'الرولونات', en: 'Rolls', ru: 'Рулоны', uk: 'Рулони', tr: 'Rulolar' },
  col_available:  { ar: 'المتاح', en: 'Available', ru: 'Доступно', uk: 'Доступно', tr: 'Mevcut' },
  col_status:     { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  col_cost:       { ar: 'سعر التكلفة/متر', en: 'Cost/Meter', ru: 'Стоимость/метр', uk: 'Вартість/метр', tr: 'Maliyet/Metre' },
  col_sell:       { ar: 'سعر البيع', en: 'Sell Price', ru: 'Цена продажи', uk: 'Ціна продажу', tr: 'Satış Fiyatı' },
  col_wholesale:  { ar: 'سعر الجملة', en: 'Wholesale', ru: 'Оптовая', uk: 'Оптова', tr: 'Toptan' },
  col_half_w:     { ar: 'نصف الجملة', en: 'Half Wholesale', ru: 'Полуоптовая', uk: 'Напівоптова', tr: 'Yarı Toptan' },
  col_special:    { ar: 'سعر خاص', en: 'Special Price', ru: 'Специальная', uk: 'Спеціальна', tr: 'Özel Fiyat' },
  col_cost_price: { ar: 'سعر التكلفة', en: 'Cost Price', ru: 'Себестоимость', uk: 'Собівартість', tr: 'Maliyet' },
  col_total_val:  { ar: 'القيمة الإجمالية', en: 'Total Value', ru: 'Общая стоимость', uk: 'Загальна вартість', tr: 'Toplam Değer' },
  col_container:  { ar: 'الحاوية', en: 'Container', ru: 'Контейнер', uk: 'Контейнер', tr: 'Konteyner' },
  // Table headers
  material_col:   { ar: 'المادة', en: 'Material', ru: 'Материал', uk: 'Матеріал', tr: 'Malzeme' },
  avail_meters:   { ar: 'المتاح (م)', en: 'Available (m)', ru: 'Доступно (м)', uk: 'Доступно (м)', tr: 'Mevcut (m)' },
  sell_price_col:     { ar: 'سعر البيع', en: 'Sell Price', ru: 'Цена продажи', uk: 'Ціна продажу', tr: 'Satış Fiyatı' },
  cost_per_m:     { ar: 'تكلفة/متر', en: 'Cost/m', ru: 'Стоимость/м', uk: 'Вартість/м', tr: 'Maliyet/m' },
  total_value:    { ar: 'قيمة إجمالية', en: 'Total Value', ru: 'Общая стоимость', uk: 'Загальна вартість', tr: 'Toplam Değer' },
  half_w:         { ar: 'نصف جملة', en: 'Half W.', ru: 'Полуопт.', uk: 'Напівопт.', tr: 'Yarı T.' },
  container:      { ar: 'حاوية', en: 'Container', ru: 'Контейнер', uk: 'Контейнер', tr: 'Konteyner' },
  stock_value:    { ar: 'قيمة المخزون', en: 'Stock Value', ru: 'Стоимость запасов', uk: 'Вартість запасів', tr: 'Stok Değeri' },
  exported:       { ar: 'تم تصدير', en: 'Exported', ru: 'Экспортировано', uk: 'Експортовано', tr: 'Dışa aktarıldı' },
  materials_word: { ar: 'مادة', en: 'materials', ru: 'материалов', uk: 'матеріалів', tr: 'malzeme' },
  roll_load_err:  { ar: 'فشل جلب بيانات الرولون', en: 'Failed to load roll data', ru: 'Ошибка загрузки данных рулона', uk: 'Помилка завантаження даних рулону', tr: 'Rulo verisi yüklenemedi' },
  loss:           { ar: '⚠ خسارة', en: '⚠ Loss', ru: '⚠ Убыток', uk: '⚠ Збиток', tr: '⚠ Zarar' },
  code_label_alt:     { ar: 'الكود', en: 'Code', ru: 'Код', uk: 'Код', tr: 'Kod' },
  purchase:       { ar: 'سعر الشراء', en: 'Purchase', ru: 'Закупочная', uk: 'Закупівельна', tr: 'Alış Fiyatı' },
  // ═══ Receipts & Deliveries Page ═══
  rd_title:       { ar: 'أذون الاستلام والتسليم', en: 'Receipts & Deliveries', ru: 'Приёмка и отгрузка', uk: 'Прийом і відвантаження', tr: 'Giriş & Çıkış' },
  rd_subtitle:    { ar: 'الأذونات المعلقة بانتظار التعامل المخزني', en: 'Pending documents waiting for warehouse processing', ru: 'Ожидающие документы для складской обработки', uk: 'Очікуючі документи для складської обробки', tr: 'Depo işleme bekleyen belgeler' },
  rd_updated:     { ar: 'آخر تحديث:', en: 'Updated:', ru: 'Обновлено:', uk: 'Оновлено:', tr: 'Güncellendi:' },
  rd_refresh:     { ar: 'تحديث', en: 'Refresh', ru: 'Обновить', uk: 'Оновити', tr: 'Yenile' },
  rd_receipt:     { ar: 'إذن استلام', en: 'Receipt', ru: 'Приёмка', uk: 'Прийом', tr: 'Giriş' },
  rd_delivery:    { ar: 'إذن تسليم', en: 'Delivery', ru: 'Отгрузка', uk: 'Відвантаження', tr: 'Çıkış' },
  rd_total_amt:   { ar: 'الإجمالي', en: 'Total Amount', ru: 'Итого', uk: 'Всього', tr: 'Toplam Tutar' },
  // Summary cards
  rd_purchases:   { ar: 'مشتريات', en: 'Purchases', ru: 'Закупки', uk: 'Закупівлі', tr: 'Alımlar' },
  rd_sales:       { ar: 'مبيعات', en: 'Sales', ru: 'Продажи', uk: 'Продажі', tr: 'Satışlar' },
  rd_containers:  { ar: 'كونتينرات', en: 'Containers', ru: 'Контейнеры', uk: 'Контейнери', tr: 'Konteynerler' },
  rd_transfers:   { ar: 'مناقلات', en: 'Transfers', ru: 'Перемещения', uk: 'Переміщення', tr: 'Transferler' },
  // Tab filters
  rd_tab_all:     { ar: 'الكل', en: 'All', ru: 'Все', uk: 'Усі', tr: 'Tümü' },
  rd_tab_purch:   { ar: 'استلام مشتريات', en: 'Purchases', ru: 'Закупки', uk: 'Закупівлі', tr: 'Alımlar' },
  rd_tab_sales:   { ar: 'تسليم مبيعات', en: 'Sales', ru: 'Продажи', uk: 'Продажі', tr: 'Satışlar' },
  rd_tab_cont:    { ar: 'استلام كونتينرات', en: 'Containers', ru: 'Контейнеры', uk: 'Контейнери', tr: 'Konteynerler' },
  rd_tab_trans:   { ar: 'مناقلات', en: 'Transfers', ru: 'Перемещения', uk: 'Переміщення', tr: 'Transferler' },
  // Table columns
  rd_doc_num:     { ar: 'رقم المستند', en: 'Document #', ru: 'Документ №', uk: 'Документ №', tr: 'Belge No' },
  rd_party:       { ar: 'الجهة', en: 'Party', ru: 'Контрагент', uk: 'Контрагент', tr: 'Taraf' },
  rd_amount:      { ar: 'المبلغ', en: 'Amount', ru: 'Сумма', uk: 'Сума', tr: 'Tutar' },
  rd_date:        { ar: 'التاريخ', en: 'Date', ru: 'Дата', uk: 'Дата', tr: 'Tarih' },
  rd_doc_status:  { ar: 'حالة المستند', en: 'Doc Status', ru: 'Статус документа', uk: 'Статус документа', tr: 'Belge Durumu' },
  rd_receipt_st:  { ar: 'حالة الاستلام', en: 'Receipt', ru: 'Статус приёмки', uk: 'Статус прийому', tr: 'Alım Durumu' },
  // Completed columns
  rd_grn:         { ar: 'رقم إذن الاستلام', en: 'GRN #', ru: 'ПН №', uk: 'ПН №', tr: 'GRN No' },
  rd_source:      { ar: 'المصدر', en: 'Source', ru: 'Источник', uk: 'Джерело', tr: 'Kaynak' },
  rd_cont_src:    { ar: '📦 كونتينر', en: '📦 Container', ru: '📦 Контейнер', uk: '📦 Контейнер', tr: '📦 Konteyner' },
  rd_inv_src:     { ar: '📄 فاتورة', en: '📄 Invoice', ru: '📄 Счёт', uk: '📄 Рахунок', tr: '📄 Fatura' },
  rd_order_src:   { ar: '📋 طلب', en: '📋 Order', ru: '📋 Заказ', uk: '📋 Замовлення', tr: '📋 Sipariş' },
  rd_qty_m:       { ar: 'الكمية (م)', en: 'Qty (m)', ru: 'Кол-во (м)', uk: 'К-ть (м)', tr: 'Miktar (m)' },
  rd_completed:   { ar: 'تاريخ الاستلام', en: 'Completed', ru: 'Завершено', uk: 'Завершено', tr: 'Tamamlandı' },
  // Status badges
  st_confirmed:   { ar: 'مؤكدة', en: 'Confirmed', ru: 'Подтверждено', uk: 'Підтверджено', tr: 'Onaylandı' },
  st_loading:     { ar: 'قيد التحميل', en: 'Loading', ru: 'Загрузка', uk: 'Завантаження', tr: 'Yükleniyor' },
  st_shipped:     { ar: 'في الطريق', en: 'Shipped', ru: 'Отправлено', uk: 'Відправлено', tr: 'Gönderildi' },
  st_sent_branch: { ar: 'أُرسلت للفرع', en: 'Sent to Branch', ru: 'Отправлено в филиал', uk: 'Надіслано у філію', tr: 'Şubeye Gönderildi' },
  st_in_delivery: { ar: 'قيد التسليم', en: 'In Delivery', ru: 'В доставке', uk: 'В доставці', tr: 'Teslimat' },
  st_in_transit:  { ar: 'بالطريق للفرع', en: 'In Transit', ru: 'В пути', uk: 'В дорозі', tr: 'Yolda' },
  st_delivered:   { ar: 'تم التسليم', en: 'Delivered', ru: 'Доставлено', uk: 'Доставлено', tr: 'Teslim Edildi' },
  st_received:    { ar: 'تم الاستلام', en: 'Received', ru: 'Получено', uk: 'Отримано', tr: 'Alındı' },
  // Receipt statuses
  rs_in_progress: { ar: 'قيد الاستلام', en: 'In Progress', ru: 'В процессе', uk: 'В процесі', tr: 'İşlemde' },
  rs_partial:     { ar: 'استلام جزئي', en: 'Partial', ru: 'Частично', uk: 'Частково', tr: 'Kısmi' },
  rs_done:        { ar: 'مكتمل', en: 'Done', ru: 'Завершено', uk: 'Завершено', tr: 'Tamamlandı' },
  rs_pending:     { ar: 'لم يبدأ', en: 'Pending', ru: 'Ожидает', uk: 'Очікує', tr: 'Bekliyor' },
  rs_elapsed:     { ar: 'الوقت المنقضي', en: 'Elapsed Time', ru: 'Прошло времени', uk: 'Минуло часу', tr: 'Geçen Süre' },
  rs_since_conf:  { ar: 'منذ التأكيد', en: 'Since confirmed', ru: 'С подтверждения', uk: 'З підтвердження', tr: 'Onaydan beri' },
  rs_since_disp:  { ar: 'منذ الإخراج', en: 'Since dispatch', ru: 'С отправки', uk: 'З відправки', tr: 'Gönderimden beri' },
  // Action buttons
  act_view:       { ar: 'عرض', en: 'View', ru: 'Просмотр', uk: 'Перегляд', tr: 'Görüntüle' },
  act_view_src:   { ar: 'عرض المستند المرجعي', en: 'View source document', ru: 'Просмотр исходного документа', uk: 'Переглянути вихідний документ', tr: 'Kaynak belgeyi görüntüle' },
  act_receive:    { ar: 'استلام', en: 'Receive', ru: 'Принять', uk: 'Прийняти', tr: 'Teslim Al' },
  act_continue:   { ar: 'متابعة', en: 'Continue', ru: 'Продолжить', uk: 'Продовжити', tr: 'Devam Et' },
  act_deliver:    { ar: 'تسليم', en: 'Deliver', ru: 'Отгрузить', uk: 'Відвантажити', tr: 'Teslim Et' },
  act_cont_del:   { ar: 'متابعة التسليم', en: 'Continue', ru: 'Продолжить', uk: 'Продовжити', tr: 'Devam Et' },
  act_dispatch:   { ar: 'تسليم من المستودع', en: 'Dispatch', ru: 'Отправить', uk: 'Відправити', tr: 'Gönder' },
  act_ship:       { ar: 'إرسال', en: 'Ship', ru: 'Отправить', uk: 'Відправити', tr: 'Gönder' },
  act_conf_recv:  { ar: 'تأكيد الاستلام', en: 'Confirm Receipt', ru: 'Подтвердить приём', uk: 'Підтвердити прийом', tr: 'Alımı Onayla' },
  act_process:    { ar: 'معالجة', en: 'Process', ru: 'Обработать', uk: 'Обробити', tr: 'İşle' },
  // Elapsed time units
  time_m:         { ar: 'د', en: 'm', ru: 'м', uk: 'хв', tr: 'dk' },
  time_h:         { ar: 'س', en: 'h', ru: 'ч', uk: 'год', tr: 'sa' },
  time_d:         { ar: 'يوم', en: 'd', ru: 'д', uk: 'д', tr: 'gün' },
  // Error messages
  err_transfer_nf:  { ar: 'المناقلة غير موجودة', en: 'Transfer not found', ru: 'Перемещение не найдено', uk: 'Переміщення не знайдено', tr: 'Transfer bulunamadı' },
  err_container_nf: { ar: 'الكونتينر غير موجود', en: 'Container not found', ru: 'Контейнер не найден', uk: 'Контейнер не знайдений', tr: 'Konteyner bulunamadı' },
  err_doc_nf:       { ar: 'المستند غير موجود في قاعدة البيانات', en: 'Document not found in database', ru: 'Документ не найден в базе данных', uk: 'Документ не знайдено в базі даних', tr: 'Belge veritabanında bulunamadı' },
  err_doc_load:     { ar: 'خطأ في تحميل المستند', en: 'Error loading document', ru: 'Ошибка загрузки документа', uk: 'Помилка завантаження документа', tr: 'Belge yükleme hatası' },
  rd_search:        { ar: 'بحث بالمرجع، المورد، أو الوصف...', en: 'Search by reference or supplier...', ru: 'Поиск по номеру, поставщику...', uk: 'Пошук за номером, постачальником...', tr: 'Referans veya tedarikçiye göre ara...' },
  rd_receipt_btn:   { ar: 'الاستلام من المخزن', en: 'Material Receipt', ru: 'Приёмка материалов', uk: 'Прийом матеріалів', tr: 'Malzeme Girişi' },
  // ═══ Stock Movements Page ═══
  sm_title:         { ar: 'حركات المخزون', en: 'Stock Movements', ru: 'Движение запасов', uk: 'Рух запасів', tr: 'Stok Hareketleri' },
  sm_subtitle:      { ar: 'سجل شامل لجميع حركات الأصناف والمواد في المستودعات', en: 'Comprehensive record of all item and material movements', ru: 'Полный журнал всех движений товаров и материалов', uk: 'Повний журнал усіх рухів товарів і матеріалів', tr: 'Tüm malzeme hareketlerinin kapsamlı kaydı' },
  sm_warehouse:     { ar: 'المستودع', en: 'Warehouse', ru: 'Склад', uk: 'Склад', tr: 'Depo' },
  sm_period:        { ar: 'الفترة', en: 'Period', ru: 'Период', uk: 'Період', tr: 'Dönem' },
  sm_all_wh:        { ar: 'كل المستودعات', en: 'All Warehouses', ru: 'Все склады', uk: 'Усі склади', tr: 'Tüm Depolar' },
  sm_search:        { ar: 'ابحث بالصنف أو المرجع...', en: 'Search material or reference...', ru: 'Поиск по материалу или номеру...', uk: 'Пошук за матеріалом або номером...', tr: 'Malzeme veya referans ara...' },
  sm_empty:         { ar: 'لم يتم العثور على حركات مطابقة', en: 'No movements found', ru: 'Движения не найдены', uk: 'Рухів не знайдено', tr: 'Hareket bulunamadı' },
  // Table columns
  sm_date:          { ar: 'التاريخ', en: 'Date', ru: 'Дата', uk: 'Дата', tr: 'Tarih' },
  sm_type:          { ar: 'نوع الحركة', en: 'Movement Type', ru: 'Тип движения', uk: 'Тип руху', tr: 'Hareket Türü' },
  sm_flow:          { ar: 'من → إلى', en: 'FROM → TO', ru: 'ОТКУДА → КУДА', uk: 'ЗВІДКИ → КУДИ', tr: 'KİMDEN → KİME' },
  sm_contents:      { ar: 'المحتويات', en: 'Contents', ru: 'Содержание', uk: 'Вміст', tr: 'İçerik' },
  sm_quantity:      { ar: 'الكمية', en: 'Quantity', ru: 'Количество', uk: 'Кількість', tr: 'Miktar' },
  sm_ref_party:     { ar: 'المرجع والجهة', en: 'Ref & Party', ru: 'Документ и контрагент', uk: 'Документ і контрагент', tr: 'Ref & Taraf' },
  sm_status:        { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  // Movement types
  mt_sale:          { ar: 'مبيعات', en: 'Sale', ru: 'Продажа', uk: 'Продаж', tr: 'Satış' },
  mt_sale_inv:      { ar: 'فاتورة مبيعات', en: 'Sales Invoice', ru: 'Счёт продажи', uk: 'Рахунок продажу', tr: 'Satış Faturası' },
  mt_issue:         { ar: 'صرف بضاعة', en: 'Issue', ru: 'Отпуск', uk: 'Видача', tr: 'Çıkış' },
  mt_delivery:      { ar: 'تسليم', en: 'Delivery', ru: 'Доставка', uk: 'Доставка', tr: 'Teslimat' },
  mt_receipt:       { ar: 'استلام', en: 'Receipt', ru: 'Приёмка', uk: 'Прийом', tr: 'Giriş' },
  mt_purchase:      { ar: 'مشتريات', en: 'Purchase', ru: 'Закупка', uk: 'Закупівля', tr: 'Alım' },
  mt_purchase_inv:  { ar: 'فاتورة شراء', en: 'Purchase Invoice', ru: 'Счёт закупки', uk: 'Рахунок закупівлі', tr: 'Alım Faturası' },
  mt_return:        { ar: 'مرتجع', en: 'Return', ru: 'Возврат', uk: 'Повернення', tr: 'İade' },
  mt_container:     { ar: 'كونتينر', en: 'Container', ru: 'Контейнер', uk: 'Контейнер', tr: 'Konteyner' },
  mt_container_rec: { ar: 'استلام كونتينر', en: 'Container Receipt', ru: 'Приёмка контейнера', uk: 'Прийом контейнера', tr: 'Konteyner Girişi' },
  mt_grn:           { ar: 'إذن استلام', en: 'GRN', ru: 'ПН', uk: 'ПН', tr: 'GRN' },
  mt_transfer:      { ar: 'مناقلة', en: 'Transfer', ru: 'Перемещение', uk: 'Переміщення', tr: 'Transfer' },
  mt_transfer_in:   { ar: 'مناقلة واردة', en: 'Transfer In', ru: 'Входящее перемещение', uk: 'Вхідне переміщення', tr: 'Gelen Transfer' },
  mt_transfer_out:  { ar: 'مناقلة صادرة', en: 'Transfer Out', ru: 'Исходящее перемещение', uk: 'Вихідне переміщення', tr: 'Giden Transfer' },
  mt_adjustment:    { ar: 'تسوية', en: 'Adjustment', ru: 'Корректировка', uk: 'Коригування', tr: 'Düzeltme' },
  mt_adj_in:        { ar: 'تسوية واردة', en: 'Adj. In', ru: 'Корр. приход', uk: 'Корег. прихід', tr: 'Düz. Giriş' },
  mt_adj_out:       { ar: 'تسوية صادرة', en: 'Adj. Out', ru: 'Корр. расход', uk: 'Корег. витрата', tr: 'Düz. Çıkış' },
  mt_opening_bal:   { ar: 'بضاعة أول المدة', en: 'Opening Balance', ru: 'Начальный остаток', uk: 'Початковий залишок', tr: 'Açılış Bakiyesi' },
  mt_sales_del:     { ar: 'تسليم مبيعات', en: 'Sales Delivery', ru: 'Отгрузка продаж', uk: 'Відвантаження продажів', tr: 'Satış Teslimatı' },
  // Status badges
  sm_shipped:       { ar: 'مرسلة', en: 'Shipped', ru: 'Отправлено', uk: 'Відправлено', tr: 'Gönderildi' },
  sm_received:      { ar: 'مستلمة', en: 'Received', ru: 'Получено', uk: 'Отримано', tr: 'Alındı' },
  sm_completed:     { ar: 'مكتمل', en: 'Completed', ru: 'Завершено', uk: 'Завершено', tr: 'Tamamlandı' },
  sm_pending:       { ar: 'معلق', en: 'Pending', ru: 'Ожидает', uk: 'Очікує', tr: 'Bekliyor' },
  // Inline text
  sm_items:         { ar: 'مادة', en: 'items', ru: 'позиций', uk: 'позицій', tr: 'kalem' },
  sm_rolls:         { ar: 'رول', en: 'rolls', ru: 'рулонов', uk: 'рулонів', tr: 'rulo' },
  sm_warehouses:    { ar: 'مستودعات', en: 'warehouses', ru: 'складов', uk: 'складів', tr: 'depo' },
  sm_since:         { ar: 'منذ ', en: '', ru: '', uk: '', tr: '' },
  sm_ago:           { ar: '', en: ' ago', ru: ' назад', uk: ' тому', tr: ' önce' },
  // Error messages
  err_no_linked_inv:  { ar: 'لا توجد فاتورة مرتبطة', en: 'No linked invoice found', ru: 'Связанный счёт не найден', uk: 'Пов\'язаний рахунок не знайдено', tr: 'Bağlı fatura bulunamadı' },
  err_receipt_nf:     { ar: 'لم يتم العثور على إذن الاستلام', en: 'Receipt not found', ru: 'Приёмка не найдена', uk: 'Прийом не знайдено', tr: 'Giriş bulunamadı' },
  err_no_inv_linked:  { ar: 'لا توجد فاتورة مرتبطة بالاستلام', en: 'No invoice linked to this receipt', ru: 'К приёмке не привязан счёт', uk: 'До прийому не прив\'язано рахунок', tr: 'Bu girişe bağlı fatura yok' },
  err_inv_nf:         { ar: 'لم يتم العثور على الفاتورة', en: 'Invoice not found', ru: 'Счёт не найден', uk: 'Рахунок не знайдено', tr: 'Fatura bulunamadı' },
  err_no_linked_sale: { ar: 'لم يتم العثور على فاتورة المبيعات المرتبطة', en: 'No linked sales invoice found', ru: 'Связанный счёт продажи не найден', uk: 'Пов\'язаний рахунок продажу не знайдено', tr: 'Bağlı satış faturası bulunamadı' },
  err_no_linked_mov:  { ar: 'لا توجد وثيقة مرتبطة بهذه الحركة', en: 'No linked document for this movement', ru: 'Нет документа для этого движения', uk: 'Немає документа для цього руху', tr: 'Bu harekete bağlı belge yok' },
  err_journal_nf:     { ar: 'لم يتم العثور على القيد', en: 'Journal entry not found', ru: 'Проводка не найдена', uk: 'Проводку не знайдено', tr: 'Muhasebe kaydı bulunamadı' },
  err_journal_load:   { ar: 'فشل تحميل القيد', en: 'Failed to load journal entry', ru: 'Ошибка загрузки проводки', uk: 'Помилка завантаження проводки', tr: 'Muhasebe kaydı yüklenemedi' },
  // ═══ Transfers Page ═══
  tf_title:           { ar: 'المناقلات', en: 'Stock Transfers', ru: 'Перемещения запасов', uk: 'Переміщення запасів', tr: 'Stok Transferleri' },
  tf_subtitle:        { ar: 'إدارة طلبات نقل المواد بين المستودعات', en: 'Manage stock transfer requests between warehouses', ru: 'Управление заявками на перемещение между складами', uk: 'Управління заявками на переміщення між складами', tr: 'Depolar arası transfer taleplerini yönetin' },
  tf_new:             { ar: 'مناقلة جديدة', en: 'New Transfer', ru: 'Новое перемещение', uk: 'Нове переміщення', tr: 'Yeni Transfer' },
  // Summary cards & tabs
  tf_draft:           { ar: 'مسودة', en: 'Draft', ru: 'Черновик', uk: 'Чернетка', tr: 'Taslak' },
  tf_loading:         { ar: 'قيد التحميل', en: 'Loading', ru: 'Загрузка', uk: 'Завантаження', tr: 'Yükleniyor' },
  tf_shipped:         { ar: 'مرسلة', en: 'Shipped', ru: 'Отправлено', uk: 'Відправлено', tr: 'Gönderildi' },
  tf_confirmed:       { ar: 'مؤكد', en: 'Confirmed', ru: 'Подтверждено', uk: 'Підтверджено', tr: 'Onaylandı' },
  tf_received:        { ar: 'مستلم', en: 'Received', ru: 'Получено', uk: 'Отримано', tr: 'Alındı' },
  tf_completed:       { ar: 'مكتمل', en: 'Completed', ru: 'Завершено', uk: 'Завершено', tr: 'Tamamlandı' },
  tf_cancelled:       { ar: 'ملغي', en: 'Cancelled', ru: 'Отменено', uk: 'Скасовано', tr: 'İptal Edildi' },
  // Direction filter
  tf_direction:       { ar: 'الاتجاه', en: 'Direction', ru: 'Направление', uk: 'Напрямок', tr: 'Yön' },
  tf_dir_all:         { ar: 'الكل', en: 'All', ru: 'Все', uk: 'Усі', tr: 'Tümü' },
  tf_dir_out:         { ar: 'صادرة (من مستودعي)', en: 'Outgoing (from my warehouse)', ru: 'Исходящие (с моего склада)', uk: 'Вихідні (з мого складу)', tr: 'Giden (deposundan)' },
  tf_dir_in:          { ar: 'واردة (إلى مستودعي)', en: 'Incoming (to my warehouse)', ru: 'Входящие (на мой склад)', uk: 'Вхідні (на мій склад)', tr: 'Gelen (deposuna)' },
  // Table columns
  tf_col_num:         { ar: 'الرقم', en: '#', ru: '№', uk: '№', tr: '#' },
  tf_col_from:        { ar: 'من المستودع', en: 'FROM', ru: 'ОТКУДА', uk: 'ЗВІДКИ', tr: 'KİMDEN' },
  tf_col_to:          { ar: 'إلى المستودع', en: 'TO', ru: 'КУДА', uk: 'КУДИ', tr: 'KİME' },
  tf_col_date:        { ar: 'التاريخ', en: 'Date', ru: 'Дата', uk: 'Дата', tr: 'Tarih' },
  tf_col_items:       { ar: 'الأصناف', en: 'Items', ru: 'Позиции', uk: 'Позиції', tr: 'Kalemler' },
  tf_col_status:      { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  // Search & actions
  tf_search:          { ar: 'بحث برقم المناقلة...', en: 'Search by transfer number...', ru: 'Поиск по номеру перемещения...', uk: 'Пошук за номером переміщення...', tr: 'Transfer numarasına göre ara...' },
  tf_del_draft:       { ar: 'حذف المسودة', en: 'Delete draft', ru: 'Удалить черновик', uk: 'Видалити чернетку', tr: 'Taslağı sil' },
  // Confirmation & error messages
  tf_err_no_del:      { ar: '🚫 لا يمكن حذف مناقلة مؤكدة أو مُرسلة', en: '🚫 Cannot delete a confirmed/shipped transfer', ru: '🚫 Нельзя удалить подтверждённое/отправленное перемещение', uk: '🚫 Не можна видалити підтверджене/відправлене переміщення', tr: '🚫 Onaylanmış/gönderilmiş transfer silinemez' },
  tf_confirm_del:     { ar: 'هل أنت متأكد من حذف هذه المناقلة المسودة؟', en: 'Are you sure you want to delete this draft transfer?', ru: 'Вы уверены, что хотите удалить этот черновик перемещения?', uk: 'Ви впевнені, що хочете видалити цю чернетку переміщення?', tr: 'Bu taslak transferi silmek istediğinize emin misiniz?' },
  tf_deleted:         { ar: '🗑️ تم حذف المناقلة المسودة', en: '🗑️ Draft transfer deleted', ru: '🗑️ Черновик перемещения удалён', uk: '🗑️ Чернетку переміщення видалено', tr: '🗑️ Taslak transfer silindi' },
  tf_del_fail:        { ar: 'فشل في الحذف', en: 'Delete failed', ru: 'Ошибка удаления', uk: 'Помилка видалення', tr: 'Silme başarısız' },
  // ═══ Stock Count Page ═══
  sc_title:           { ar: 'الجرد المخزني', en: 'Stock Count', ru: 'Инвентаризация', uk: 'Інвентаризація', tr: 'Stok Sayımı' },
  sc_subtitle:        { ar: 'إدارة وتنفيذ جرد المستودعات', en: 'Manage and execute warehouse inventory counts', ru: 'Управление инвентаризацией склада', uk: 'Управління інвентаризацією складу', tr: 'Depo stok sayımlarını yönetin' },
  sc_new:             { ar: 'جرد جديد', en: 'New Count', ru: 'Новый подсчёт', uk: 'Новий підрахунок', tr: 'Yeni Sayım' },
  // Status labels
  sc_planned:         { ar: 'مخطط', en: 'Planned', ru: 'Запланировано', uk: 'Заплановано', tr: 'Planlandı' },
  sc_in_progress:     { ar: 'جاري التنفيذ', en: 'In Progress', ru: 'Выполняется', uk: 'Виконується', tr: 'Devam Ediyor' },
  sc_completed:       { ar: 'مكتمل', en: 'Completed', ru: 'Завершено', uk: 'Завершено', tr: 'Tamamlandı' },
  sc_cancelled:       { ar: 'ملغى', en: 'Cancelled', ru: 'Отменено', uk: 'Скасовано', tr: 'İptal Edildi' },
  sc_active:          { ar: 'جاري', en: 'Active', ru: 'Активные', uk: 'Активні', tr: 'Aktif' },
  sc_done:            { ar: 'مكتمل', en: 'Done', ru: 'Готово', uk: 'Готово', tr: 'Bitti' },
  // Count modes
  sc_full:            { ar: 'جرد كامل', en: 'Full Count', ru: 'Полный подсчёт', uk: 'Повний підрахунок', tr: 'Tam Sayım' },
  sc_barcode:         { ar: 'مسح باركود', en: 'Barcode Scan', ru: 'Сканирование', uk: 'Сканування', tr: 'Barkod Tarama' },
  sc_loose:           { ar: 'مخزون سائب', en: 'Loose Stock', ru: 'Россыпь', uk: 'Розсип', tr: 'Dökme Stok' },
  sc_partial:         { ar: 'جرد جزئي', en: 'Partial Count', ru: 'Частичный подсчёт', uk: 'Частковий підрахунок', tr: 'Kısmi Sayım' },
  sc_scheduled:       { ar: 'جرد مجدول', en: 'Scheduled', ru: 'Запланированный', uk: 'Запланований', tr: 'Planlanmış' },
  // Column headers
  sc_col_num:         { ar: 'رقم الجرد', en: 'Count #', ru: '№ подсчёта', uk: '№ підрахунку', tr: 'Sayım #' },
  sc_col_wh:          { ar: 'المستودع', en: 'Warehouse', ru: 'Склад', uk: 'Склад', tr: 'Depo' },
  sc_col_type:        { ar: 'نوع الجرد', en: 'Count Type', ru: 'Тип подсчёта', uk: 'Тип підрахунку', tr: 'Sayım Türü' },
  sc_col_date:        { ar: 'التاريخ', en: 'Date', ru: 'Дата', uk: 'Дата', tr: 'Tarih' },
  sc_col_items:       { ar: 'البنود', en: 'Items', ru: 'Позиции', uk: 'Позиції', tr: 'Kalemler' },
  sc_col_status:      { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  // Actions
  sc_start:           { ar: 'بدء', en: 'Start', ru: 'Начать', uk: 'Почати', tr: 'Başla' },
  sc_continue:        { ar: 'متابعة', en: 'Continue', ru: 'Продолжить', uk: 'Продовжити', tr: 'Devam' },
  sc_report:          { ar: 'التقرير', en: 'Report', ru: 'Отчёт', uk: 'Звіт', tr: 'Rapor' },
  // Search & footer
  sc_search:          { ar: 'بحث برقم الجرد أو المستودع...', en: 'Search by count number or warehouse...', ru: 'Поиск по номеру или складу...', uk: 'Пошук за номером або складом...', tr: 'Sayım numarası veya depoya göre ara...' },
  sc_empty:           { ar: 'لا يوجد جرود بعد', en: 'No stock counts yet', ru: 'Инвентаризаций пока нет', uk: 'Інвентаризацій поки немає', tr: 'Henüz stok sayımı yok' },
  sc_count:           { ar: 'جرد', en: 'count', ru: 'подсчёт', uk: 'підрахунок', tr: 'sayım' },
  err_sc_load:        { ar: 'فشل تحميل بيانات الجرد', en: 'Failed to load stock count data', ru: 'Ошибка загрузки данных подсчёта', uk: 'Помилка завантаження даних підрахунку', tr: 'Stok sayım verileri yüklenemedi' },
  // ═══ Location Management Page ═══
  lm_title:           { ar: 'إدارة المواقع', en: 'Location Management', ru: 'Управление локациями', uk: 'Управління локаціями', tr: 'Konum Yönetimi' },
  lm_subtitle:        { ar: 'تنظيم المواقع داخل المستودعات (ممر / رف / طبقة / صندوق)', en: 'Organize locations within warehouses (Aisle/Rack/Shelf/Bin)', ru: 'Организация зон хранения (Проход/Стеллаж/Полка/Ячейка)', uk: 'Організація зон зберігання (Прохід/Стелаж/Полиця/Комірка)', tr: 'Depo içi konumları düzenleyin (Koridor/Raf/Bölme)' },
  lm_new_loc:         { ar: 'موقع جديد', en: 'New Location', ru: 'Новая локация', uk: 'Нова локація', tr: 'Yeni Konum' },
  lm_select_wh:       { ar: 'اختر المستودع', en: 'Select Warehouse', ru: 'Выберите склад', uk: 'Оберіть склад', tr: 'Depo Seçin' },
  lm_search:          { ar: 'بحث بالكود أو الاسم...', en: 'Search by code or name...', ru: 'Поиск по коду или названию...', uk: 'Пошук за кодом або назвою...', tr: 'Kod veya adla ara...' },
  lm_structure:       { ar: 'هيكل المواقع', en: 'Location Structure', ru: 'Структура локаций', uk: 'Структура локацій', tr: 'Konum Yapısı' },
  lm_select_wh_msg:   { ar: 'اختر مستودعاً لعرض المواقع', en: 'Select a warehouse to view locations', ru: 'Выберите склад для просмотра локаций', uk: 'Оберіть склад для перегляду локацій', tr: 'Konumları görmek için bir depo seçin' },
  lm_no_locs:         { ar: 'لا توجد مواقع', en: 'No Locations', ru: 'Нет локаций', uk: 'Немає локацій', tr: 'Konum yok' },
  lm_no_locs_msg:     { ar: 'لم يتم العثور على مواقع لهذا المستودع', en: 'No locations found for this warehouse', ru: 'Локации для этого склада не найдены', uk: 'Локації для цього складу не знайдені', tr: 'Bu depo için konum bulunamadı' },
  lm_add_aisle:       { ar: 'إضافة ممر', en: 'Add Aisle', ru: 'Добавить проход', uk: 'Додати прохід', tr: 'Koridor Ekle' },
  lm_add_child:       { ar: 'إضافة فرعي', en: 'Add Child', ru: 'Добавить дочерний', uk: 'Додати дочірній', tr: 'Alt Öğe Ekle' },
  lm_edit:            { ar: 'تعديل', en: 'Edit', ru: 'Редактировать', uk: 'Редагувати', tr: 'Düzenle' },
  lm_delete:          { ar: 'حذف', en: 'Delete', ru: 'Удалить', uk: 'Видалити', tr: 'Sil' },
  lm_inactive:        { ar: 'غير نشط', en: 'Inactive', ru: 'Неактивно', uk: 'Неактивно', tr: 'Pasif' },
  // ═══ Accounting Journal Entries Page ═══
  je_title:           { ar: 'القيود المحاسبية', en: 'Journal Entries', ru: 'Журнальные записи', uk: 'Журнальні записи', tr: 'Yevmiye Kayıtları' },
  je_subtitle:        { ar: 'إدارة وتتبع قيود اليومية', en: 'Manage and track journal entries', ru: 'Управление журнальными записями', uk: 'Управління журнальними записами', tr: 'Yevmiye kayıtlarını yönet ve takip et' },
  je_all:             { ar: 'الكل', en: 'All', ru: 'Все', uk: 'Всі', tr: 'Tümü' },
  je_journal:         { ar: 'قيد يومية', en: 'Journal', ru: 'Журнал', uk: 'Журнал', tr: 'Yevmiye' },
  je_opening_balance: { ar: 'رصيد افتتاحي', en: 'Opening Balance', ru: 'Начальный баланс', uk: 'Початковий баланс', tr: 'Açılış Bakiyesi' },
  je_opening:         { ar: 'افتتاحي', en: 'Opening', ru: 'Начальный', uk: 'Початковий', tr: 'Açılış' },
  je_closing:         { ar: 'إغلاق', en: 'Closing', ru: 'Закрытие', uk: 'Закриття', tr: 'Kapanış' },
  je_receipts:        { ar: 'سندات القبض', en: 'Receipts', ru: 'Квитанции', uk: 'Квитанції', tr: 'Tahsilatlar' },
  je_receipt:         { ar: 'سند قبض', en: 'Receipt', ru: 'Квитанция', uk: 'Квитанція', tr: 'Tahsilat' },
  je_payments:        { ar: 'المدفوعات', en: 'Payments', ru: 'Платежи', uk: 'Платежі', tr: 'Ödemeler' },
  je_payment:         { ar: 'سند صرف', en: 'Payment', ru: 'Платеж', uk: 'Платіж', tr: 'Ödeme' },
  je_cash:            { ar: 'يومية صندوق', en: 'Cash Journal', ru: 'Кассовый журнал', uk: 'Касовий журнал', tr: 'Kasa Defteri' },
  je_sales:           { ar: 'مبيعات', en: 'Sales', ru: 'Продажи', uk: 'Продажі', tr: 'Satışlar' },
  je_sales_invoice:   { ar: 'فاتورة مبيعات', en: 'Sales Inv.', ru: 'Счет продаж', uk: 'Рахунок продажів', tr: 'Satış Fat.' },
  je_sales_cogs:      { ar: 'تكلفة مبيعات', en: 'COGS', ru: 'Себестоимость', uk: 'Собівартість', tr: 'SMM' },
  je_purchase:        { ar: 'مشتريات', en: 'Purchase', ru: 'Закупки', uk: 'Закупівлі', tr: 'Alımlar' },
  je_purchase_invoice:{ ar: 'ف. مشتريات', en: 'Purch. Inv.', ru: 'Счет закупок', uk: 'Рахунок закупівель', tr: 'Alım Fat.' },
  je_cont_exp:        { ar: 'م. كونتينر', en: 'Cont. Exp.', ru: 'Расх. конт.', uk: 'Витр. конт.', tr: 'Kont. Gid.' },
  je_container:       { ar: 'كونتينر', en: 'Container', ru: 'Контейнер', uk: 'Контейнер', tr: 'Konteyner' },
  je_cont_tax:        { ar: 'ضريبة كونتينر', en: 'Cont. Tax', ru: 'Налог конт.', uk: 'Податок конт.', tr: 'Kont. Verg.' },
  je_cont_close:      { ar: 'إغلاق كونتينر', en: 'Cont. Close', ru: 'Закр. конт.', uk: 'Закр. конт.', tr: 'Kont. Kapanış' },
  je_goods_receipt:   { ar: 'استلام بضاعة', en: 'Goods Receipt', ru: 'Поступление', uk: 'Надходження', tr: 'Mal Girişi' },
  je_return:          { ar: 'مرتجع', en: 'Return', ru: 'Возврат', uk: 'Повернення', tr: 'İade' },
  je_expense:         { ar: 'مصروف', en: 'Expense', ru: 'Расход', uk: 'Витрати', tr: 'Gider' },
  je_transfer:        { ar: 'تحويل', en: 'Transfer', ru: 'Перевод', uk: 'Переказ', tr: 'Transfer' },
  je_exchange:        { ar: 'صرافة', en: 'Exchange', ru: 'Обмен', uk: 'Обмін', tr: 'Döviz' },
  je_depreciation:    { ar: 'إهلاك', en: 'Depreciation', ru: 'Амортизация', uk: 'Амортизація', tr: 'Amortisman' },
  je_payroll:         { ar: 'رواتب', en: 'Payroll', ru: 'Зарплата', uk: 'Зарплата', tr: 'Maaşlar' },
  je_adjustment:      { ar: 'تسوية', en: 'Adjustment', ru: 'Корректировка', uk: 'Коригування', tr: 'Düzeltme' },
  je_vat:             { ar: 'تسوية ضريبة', en: 'VAT Settlement', ru: 'Отчет по НДС', uk: 'Звіт з ПДВ', tr: 'KDV Mutabakatı' },
  je_mixed:           { ar: 'مختلف', en: 'Mixed', ru: 'Смешанный', uk: 'Змішаний', tr: 'Karma' },
  je_manual:          { ar: 'يدوي', en: 'Manual', ru: 'Вручную', uk: 'Вручну', tr: 'Manuel' },
  je_t_debit:         { ar: 'إجمالي المدين', en: 'Total Debit', ru: 'Итого дебет', uk: 'Всього дебет', tr: 'Toplam Borç' },
  je_t_credit:        { ar: 'إجمالي الدائن', en: 'Total Credit', ru: 'Итого кредит', uk: 'Всього кредит', tr: 'Toplam Alacak' },
  je_t_net:           { ar: 'صافي الحركة', en: 'Net Movement', ru: 'Чистое движение', uk: 'Чистий рух', tr: 'Net Hareket' },
  je_t_count:         { ar: 'عدد القيود', en: 'Entries', ru: 'Записи', uk: 'Записи', tr: 'Kayıtlar' },
  je_post:            { ar: 'مرحّل', en: 'Posted', ru: 'Проведено', uk: 'Проведено', tr: 'İşlendi' },
  je_dft:             { ar: 'مسودة', en: 'Draft', ru: 'Черновик', uk: 'Чернетка', tr: 'Taslak' },
  je_pend:            { ar: 'معلّق', en: 'Pending', ru: 'В ожидании', uk: 'В очікуванні', tr: 'Beklemede' },
  je_canc:            { ar: 'ملغي', en: 'Cancelled', ru: 'Отменено', uk: 'Скасовано', tr: 'İptal' },
  je_debit:           { ar: 'المدين', en: 'Debit', ru: 'Дебет', uk: 'Дебет', tr: 'Borç' },
  je_credit:          { ar: 'الدائن', en: 'Credit', ru: 'Кредит', uk: 'Кредит', tr: 'Alacak' },
  je_date:            { ar: 'التاريخ', en: 'Date', ru: 'Дата', uk: 'Дата', tr: 'Tarih' },
  je_desc:            { ar: 'البيان', en: 'Description', ru: 'Описание', uk: 'Опис', tr: 'Açıklama' },
  je_entry_no:        { ar: 'رقم القيد', en: 'Entry #', ru: 'Запись #', uk: 'Запис #', tr: 'Kayıt No' },
  je_ref:             { ar: 'المرجع', en: 'Reference', ru: 'Ссылка', uk: 'Посилання', tr: 'Referans' },
  je_status:          { ar: 'الحالة', en: 'Status', ru: 'Статус', uk: 'Статус', tr: 'Durum' },
  je_type:            { ar: 'النوع', en: 'Type', ru: 'Тип', uk: 'Тип', tr: 'Tür' },
  je_search:          { ar: 'بحث في القيود...', en: 'Search entries...', ru: 'Поиск записей...', uk: 'Пошук записів...', tr: 'Kayıtlarda ara...' },
  je_show_sys:        { ar: 'إظهار قيود النظام', en: 'Show System', ru: 'Показать системные', uk: 'Показати системні', tr: 'Sistemi Göster' },
  je_hide_sys:        { ar: 'إخفاء قيود النظام', en: 'Hide System', ru: 'Скрыть системные', uk: 'Сховати системні', tr: 'Sistemi Gizle' },
  je_entries:         { ar: 'قيد', en: 'entries', ru: 'записей', uk: 'записів', tr: 'kayıt' },
  je_dr:              { ar: 'مدين: ', en: 'Dr: ', ru: 'Дт: ', uk: 'Дт: ', tr: 'B: ' },
  je_cr:              { ar: 'دائن: ', en: 'Cr: ', ru: 'Кт: ', uk: 'Кт: ', tr: 'A: ' },
  je_diff:            { ar: 'فرق: ', en: 'Diff: ', ru: 'Разн: ', uk: 'Різн: ', tr: 'Fark: ' },
  je_others:          { ar: 'آخرين', en: 'more', ru: 'еще', uk: 'ще', tr: 'diğer' },
  je_no_match:        { ar: 'لا توجد قيود مطابقة', en: 'No matching entries', ru: 'Нет совпадений', uk: 'Немає збігів', tr: 'Eşleşen kayıt yok' },
  je_select_cur:      { ar: 'اختر عملة', en: 'Select currency', ru: 'Выберите валюту', uk: 'Виберіть валюту', tr: 'Para birimi seçin' },
  je_select_cur_totals:{ ar: 'اختر عملة لعرض المجاميع', en: 'Select currency for totals', ru: 'Выберите валюту для итогов', uk: 'Виберіть валюту для підсумків', tr: 'Toplamlar için para birimi seçin' },
  // ═══ Accounting Settings ═══
  stg_saved                          : { ar: 'تم الحفظ', en: 'Saved', ru: 'Saved', uk: 'Saved', tr: 'Saved' },
  stg_settings_saved_successfully    : { ar: 'تم حفظ الإعدادات بنجاح', en: 'Settings saved successfully', ru: 'Settings saved successfully', uk: 'Settings saved successfully', tr: 'Settings saved successfully' },
  stg_error                          : { ar: 'خطأ', en: 'Error', ru: 'Error', uk: 'Error', tr: 'Error' },
  stg_failed_to_save_settings        : { ar: 'حدث خطأ في حفظ الإعدادات', en: 'Failed to save settings', ru: 'Failed to save settings', uk: 'Failed to save settings', tr: 'Failed to save settings' },
  stg_en                             : { ar: 'ar', en: 'en', ru: 'en', uk: 'en', tr: 'en' },
  stg_cannot_remove                  : { ar: 'لا يمكن الحذف', en: 'Cannot Remove', ru: 'Cannot Remove', uk: 'Cannot Remove', tr: 'Cannot Remove' },
  stg_cannot_remove_base_currency    : { ar: 'لا يمكن إزالة العملة الأساسية', en: 'Cannot remove base currency', ru: 'Cannot remove base currency', uk: 'Cannot remove base currency', tr: 'Cannot remove base currency' },
  stg_number_format                  : { ar: 'تنسيق الأرقام', en: 'Number Format', ru: 'Number Format', uk: 'Number Format', tr: 'Number Format' },
  stg_number_and_date_display_settin : { ar: 'إعدادات عرض الأرقام والتواريخ في النظام', en: 'Number and date display settings', ru: 'Number and date display settings', uk: 'Number and date display settings', tr: 'Number and date display settings' },
  stg_decimal_places                 : { ar: 'دقة الأرقام العشرية', en: 'Decimal Places', ru: 'Decimal Places', uk: 'Decimal Places', tr: 'Decimal Places' },
  stg_date_format                    : { ar: 'تنسيق التاريخ', en: 'Date Format', ru: 'Date Format', uk: 'Date Format', tr: 'Date Format' },
  stg_workflow                       : { ar: 'سير العمل', en: 'Workflow', ru: 'Workflow', uk: 'Workflow', tr: 'Workflow' },
  stg_auto_posting_and_approval_sett : { ar: 'إعدادات الترحيل التلقائي والموافقات', en: 'Auto-posting and approval settings', ru: 'Auto-posting and approval settings', uk: 'Auto-posting and approval settings', tr: 'Auto-posting and approval settings' },
  stg_auto_post_entries              : { ar: 'ترحيل تلقائي للقيود', en: 'Auto-post Entries', ru: 'Auto-post Entries', uk: 'Auto-post Entries', tr: 'Auto-post Entries' },
  stg_auto_post_entries_after_saving : { ar: 'ترحيل القيود تلقائياً بعد الحفظ', en: 'Auto-post entries after saving', ru: 'Auto-post entries after saving', uk: 'Auto-post entries after saving', tr: 'Auto-post entries after saving' },
  stg_require_approval               : { ar: 'طلب موافقة', en: 'Require Approval', ru: 'Require Approval', uk: 'Require Approval', tr: 'Require Approval' },
  stg_require_approval_before_postin : { ar: 'طلب موافقة قبل الترحيل', en: 'Require approval before posting', ru: 'Require approval before posting', uk: 'Require approval before posting', tr: 'Require approval before posting' },
  stg_configured_of_total_accounts_c : { ar: '${configured} من ${total} حسابات مُعيّنة', en: '${configured} of ${total} accounts configured', ru: '${configured} of ${total} accounts configured', uk: '${configured} of ${total} accounts configured', tr: '${configured} of ${total} accounts configured' },
  stg_currency_settings              : { ar: 'إعدادات العملات', en: 'Currency Settings', ru: 'Currency Settings', uk: 'Currency Settings', tr: 'Currency Settings' },
  stg_base_and_local_currency_locked : { ar: 'العملة الرئيسية والعملة المحلية — تُقفل بعد أول حركة محاسبية', en: 'Base and local currency — locked after first journal entry', ru: 'Base and local currency — locked after first journal entry', uk: 'Base and local currency — locked after first journal entry', tr: 'Base and local currency — locked after first journal entry' },
  stg_base_currency                  : { ar: 'العملة الرئيسية', en: 'Base Currency', ru: 'Base Currency', uk: 'Base Currency', tr: 'Base Currency' },
  stg_locked                         : { ar: 'مقفلة', en: 'Locked', ru: 'Locked', uk: 'Locked', tr: 'Locked' },
  stg_select_currency                : { ar: 'اختر العملة...', en: 'Select currency...', ru: 'Select currency...', uk: 'Select currency...', tr: 'Select currency...' },
  stg_cannot_change_base_currency_af : { ar: '🔒 لا يمكن تغيير العملة الرئيسية بعد وجود قيود محاسبية', en: '🔒 Cannot change base currency after journal entries exist', ru: '🔒 Cannot change base currency after journal entries exist', uk: '🔒 Cannot change base currency after journal entries exist', tr: '🔒 Cannot change base currency after journal entries exist' },
  stg_primary_accounting_currency_al : { ar: 'عملة المحاسبة الأساسية — جميع التقارير تصدر بها', en: 'Primary accounting currency — all reports are generated in this currency', ru: 'Primary accounting currency — all reports are generated in this currency', uk: 'Primary accounting currency — all reports are generated in this currency', tr: 'Primary accounting currency — all reports are generated in this currency' },
  stg_default_sales_currency         : { ar: 'عملة البيع الافتراضية', en: 'Default Sales Currency', ru: 'Default Sales Currency', uk: 'Default Sales Currency', tr: 'Default Sales Currency' },
  stg_default_currency_for_sales_inv : { ar: 'العملة المستخدمة افتراضياً في فواتير المبيعات', en: 'Default currency for sales invoices', ru: 'Default currency for sales invoices', uk: 'Default currency for sales invoices', tr: 'Default currency for sales invoices' },
  stg_default_purchase_currency      : { ar: 'عملة الشراء الافتراضية', en: 'Default Purchase Currency', ru: 'Default Purchase Currency', uk: 'Default Purchase Currency', tr: 'Default Purchase Currency' },
  stg_default_currency_for_purchase_ : { ar: 'العملة المستخدمة افتراضياً في فواتير المشتريات', en: 'Default currency for purchase invoices', ru: 'Default currency for purchase invoices', uk: 'Default currency for purchase invoices', tr: 'Default currency for purchase invoices' },
  stg_supported_currencies           : { ar: 'العملات المدعومة', en: 'Supported Currencies', ru: 'Supported Currencies', uk: 'Supported Currencies', tr: 'Supported Currencies' },
  stg_active_currencies_add_more_fro : { ar: 'العملات المفعّلة — يمكن إضافة المزيد من تبويب العملات', en: 'Active currencies — add more from the Currencies tab', ru: 'Active currencies — add more from the Currencies tab', uk: 'Active currencies — add more from the Currencies tab', tr: 'Active currencies — add more from the Currencies tab' },
  stg_financial_accounts             : { ar: 'الحسابات المالية', en: 'Financial Accounts', ru: 'Financial Accounts', uk: 'Financial Accounts', tr: 'Financial Accounts' },
  stg_cash_bank_and_receivables_paya : { ar: 'الصندوق والبنك والذمم', en: 'Cash, bank, and receivables/payables', ru: 'Cash, bank, and receivables/payables', uk: 'Cash, bank, and receivables/payables', tr: 'Cash, bank, and receivables/payables' },
  stg_cash_account                   : { ar: 'حساب الصندوق', en: 'Cash Account', ru: 'Cash Account', uk: 'Cash Account', tr: 'Cash Account' },
  stg_set                            : { ar: 'مُعيّن', en: 'Set', ru: 'Set', uk: 'Set', tr: 'Set' },
  stg_not_set                        : { ar: 'غير مُعيّن', en: 'Not set', ru: 'Not set', uk: 'Not set', tr: 'Not set' },
  stg_select_account                 : { ar: 'اختر حساب...', en: 'Select account...', ru: 'Select account...', uk: 'Select account...', tr: 'Select account...' },
  stg_used_for_cash_receipts_and_pay : { ar: 'يُستخدم في سندات القبض والصرف النقدي', en: 'Used for cash receipts and payments', ru: 'Used for cash receipts and payments', uk: 'Used for cash receipts and payments', tr: 'Used for cash receipts and payments' },
  stg_bank_account                   : { ar: 'حساب البنك', en: 'Bank Account', ru: 'Bank Account', uk: 'Bank Account', tr: 'Bank Account' },
  stg_used_for_bank_transfers_and_de : { ar: 'يُستخدم في التحويلات البنكية والإيداعات', en: 'Used for bank transfers and deposits', ru: 'Used for bank transfers and deposits', uk: 'Used for bank transfers and deposits', tr: 'Used for bank transfers and deposits' },
  stg_accounts_receivable            : { ar: 'الذمم المدينة', en: 'Accounts Receivable', ru: 'Accounts Receivable', uk: 'Accounts Receivable', tr: 'Accounts Receivable' },
  stg_customer_account_used_in_sales : { ar: 'حساب الزبائن - يُستخدم في فواتير المبيعات', en: 'Customer account - used in sales invoices', ru: 'Customer account - used in sales invoices', uk: 'Customer account - used in sales invoices', tr: 'Customer account - used in sales invoices' },
  stg_accounts_payable               : { ar: 'الذمم الدائنة', en: 'Accounts Payable', ru: 'Accounts Payable', uk: 'Accounts Payable', tr: 'Accounts Payable' },
  stg_vendor_account_used_in_purchas : { ar: 'حساب الموردين - يُستخدم في فواتير المشتريات', en: 'Vendor account - used in purchase invoices', ru: 'Vendor account - used in purchase invoices', uk: 'Vendor account - used in purchase invoices', tr: 'Vendor account - used in purchase invoices' },
  stg_operational_accounts           : { ar: 'حسابات التشغيل', en: 'Operational Accounts', ru: 'Operational Accounts', uk: 'Operational Accounts', tr: 'Operational Accounts' },
  stg_revenue_expenses_and_purchases : { ar: 'الإيرادات والمصروفات والمشتريات', en: 'Revenue, expenses, and purchases', ru: 'Revenue, expenses, and purchases', uk: 'Revenue, expenses, and purchases', tr: 'Revenue, expenses, and purchases' },
  stg_revenue_account                : { ar: 'حساب الإيرادات', en: 'Revenue Account', ru: 'Revenue Account', uk: 'Revenue Account', tr: 'Revenue Account' },
  stg_auto_used_in_sales_invoices    : { ar: 'يُستخدم تلقائياً في فواتير المبيعات', en: 'Auto-used in sales invoices', ru: 'Auto-used in sales invoices', uk: 'Auto-used in sales invoices', tr: 'Auto-used in sales invoices' },
  stg_expense_account                : { ar: 'حساب المصروفات', en: 'Expense Account', ru: 'Expense Account', uk: 'Expense Account', tr: 'Expense Account' },
  stg_used_for_general_and_operation : { ar: 'يُستخدم في المصروفات العامة والتشغيلية', en: 'Used for general and operational expenses', ru: 'Used for general and operational expenses', uk: 'Used for general and operational expenses', tr: 'Used for general and operational expenses' },
  stg_purchases_cogs                 : { ar: 'حساب المشتريات / تكلفة البضاعة', en: 'Purchases / COGS', ru: 'Purchases / COGS', uk: 'Purchases / COGS', tr: 'Purchases / COGS' },
  stg_required                       : { ar: 'مطلوب ❗', en: 'Required ❗', ru: 'Required ❗', uk: 'Required ❗', tr: 'Required ❗' },
  stg_debit_side_for_purchase_invoic : { ar: 'الجانب المدين في فواتير المشتريات — ضروري للترحيل', en: 'Debit side for purchase invoices — required for posting', ru: 'Debit side for purchase invoices — required for posting', uk: 'Debit side for purchase invoices — required for posting', tr: 'Debit side for purchase invoices — required for posting' },
  stg_tax_accounts_input_output_are_ : { ar: 'حسابات الضريبة (مدخلات / مخرجات) تُدار من ', en: 'Tax accounts (input / output) are managed in ', ru: 'Tax accounts (input / output) are managed in ', uk: 'Tax accounts (input / output) are managed in ', tr: 'Tax accounts (input / output) are managed in ' },
  stg_settings_tax_compliance        : { ar: 'الإعدادات → الضرائب والأنظمة', en: 'Settings → Tax & Compliance', ru: 'Settings → Tax & Compliance', uk: 'Settings → Tax & Compliance', tr: 'Settings → Tax & Compliance' },
  stg_inventory_account              : { ar: 'حساب المخزون', en: 'Inventory Account', ru: 'Inventory Account', uk: 'Inventory Account', tr: 'Inventory Account' },
  stg_goods_fabric_inventory_account : { ar: 'حساب البضاعة / مخزون الأقمشة', en: 'Goods / fabric inventory account', ru: 'Goods / fabric inventory account', uk: 'Goods / fabric inventory account', tr: 'Goods / fabric inventory account' },
  stg_purchases_in_transit           : { ar: 'حساب مشتريات بالطريق', en: 'Purchases in Transit', ru: 'Purchases in Transit', uk: 'Purchases in Transit', tr: 'Purchases in Transit' },
  stg_transit_account_for_internatio : { ar: 'الحساب الوسيط للفواتير الدولية (1145) — ينتقل منه للكونتينر أو المخزون عند الاستلام', en: 'Transit account for international invoices (1145) — transfers to container or inventory on receipt', ru: 'Transit account for international invoices (1145) — transfers to container or inventory on receipt', uk: 'Transit account for international invoices (1145) — transfers to container or inventory on receipt', tr: 'Transit account for international invoices (1145) — transfers to container or inventory on receipt' },
  stg_freight_in                     : { ar: 'مصاريف الشحن والنقل', en: 'Freight In', ru: 'Freight In', uk: 'Freight In', tr: 'Freight In' },
  stg_shipping_costs_on_purchases_an : { ar: 'تكاليف الشحن على المشتريات والشحنات', en: 'Shipping costs on purchases and shipments', ru: 'Shipping costs on purchases and shipments', uk: 'Shipping costs on purchases and shipments', tr: 'Shipping costs on purchases and shipments' },
  stg_advanced_accounts              : { ar: 'حسابات متقدمة', en: 'Advanced Accounts', ru: 'Advanced Accounts', uk: 'Advanced Accounts', tr: 'Advanced Accounts' },
  stg_currency_differences_retained_ : { ar: 'فروقات العملات، الأرباح المحتجزة، والسلف', en: 'Currency differences, retained earnings, and advances', ru: 'Currency differences, retained earnings, and advances', uk: 'Currency differences, retained earnings, and advances', tr: 'Currency differences, retained earnings, and advances' },
  stg_retained_earnings              : { ar: '📊 الأرباح المحتجزة', en: '📊 Retained Earnings', ru: '📊 Retained Earnings', uk: '📊 Retained Earnings', tr: '📊 Retained Earnings' },
  stg_used_for_year_end_closing_prof : { ar: 'يُستخدم عند إقفال السنة المالية — تُرحل إليه الأرباح', en: 'Used for year-end closing — profits are transferred here', ru: 'Used for year-end closing — profits are transferred here', uk: 'Used for year-end closing — profits are transferred here', tr: 'Used for year-end closing — profits are transferred here' },
  stg_customer_advances              : { ar: '🧾 سلف الزبائن', en: '🧾 Customer Advances', ru: '🧾 Customer Advances', uk: '🧾 Customer Advances', tr: '🧾 Customer Advances' },
  stg_advance_payments_from_customer : { ar: 'دفعات مقدمة من الزبائن قبل التسليم', en: 'Advance payments from customers before delivery', ru: 'Advance payments from customers before delivery', uk: 'Advance payments from customers before delivery', tr: 'Advance payments from customers before delivery' },
  stg_supplier_advances              : { ar: '🧾 سلف الموردين', en: '🧾 Supplier Advances', ru: '🧾 Supplier Advances', uk: '🧾 Supplier Advances', tr: '🧾 Supplier Advances' },
  stg_advance_payments_to_suppliers_ : { ar: 'دفعات مقدمة للموردين قبل الاستلام', en: 'Advance payments to suppliers before receipt', ru: 'Advance payments to suppliers before receipt', uk: 'Advance payments to suppliers before receipt', tr: 'Advance payments to suppliers before receipt' },
  stg_exchange_remittance_accounts   : { ar: 'حسابات الصرافة والحوالات', en: 'Exchange & Remittance Accounts', ru: 'Exchange & Remittance Accounts', uk: 'Exchange & Remittance Accounts', tr: 'Exchange & Remittance Accounts' },
  stg_exchange_module                : { ar: 'موديول الصرافة', en: 'Exchange Module', ru: 'Exchange Module', uk: 'Exchange Module', tr: 'Exchange Module' },
  stg_exchange_and_fx_difference_acc : { ar: 'حسابات الصرف وفروقات العملات — تظهر عند تفعيل موديول الصرافة', en: 'Exchange and FX difference accounts — shown when Exchange module is active', ru: 'Exchange and FX difference accounts — shown when Exchange module is active', uk: 'Exchange and FX difference accounts — shown when Exchange module is active', tr: 'Exchange and FX difference accounts — shown when Exchange module is active' },
  stg_fx_gains_exchange              : { ar: '💱 أرباح فروقات عملات - صرافة', en: '💱 FX Gains - Exchange', ru: '💱 FX Gains - Exchange', uk: '💱 FX Gains - Exchange', tr: '💱 FX Gains - Exchange' },
  stg_gains_from_direct_currency_exc : { ar: 'أرباح عمليات صرف العملات المباشرة (433)', en: 'Gains from direct currency exchange operations (433)', ru: 'Gains from direct currency exchange operations (433)', uk: 'Gains from direct currency exchange operations (433)', tr: 'Gains from direct currency exchange operations (433)' },
  stg_fx_losses_exchange             : { ar: '💱 خسائر فروقات عملات - صرافة', en: '💱 FX Losses - Exchange', ru: '💱 FX Losses - Exchange', uk: '💱 FX Losses - Exchange', tr: '💱 FX Losses - Exchange' },
  stg_losses_from_direct_currency_ex : { ar: 'خسائر عمليات صرف العملات المباشرة (543)', en: 'Losses from direct currency exchange operations (543)', ru: 'Losses from direct currency exchange operations (543)', uk: 'Losses from direct currency exchange operations (543)', tr: 'Losses from direct currency exchange operations (543)' },
  stg_remittance_accounts            : { ar: 'حسابات الحوالات', en: 'Remittance Accounts', ru: 'Remittance Accounts', uk: 'Remittance Accounts', tr: 'Remittance Accounts' },
  stg_commissions_and_receivables_pa : { ar: 'العمولات والذمم المتعلقة بالحوالات الصادرة والواردة', en: 'Commissions and receivables/payables for remittances', ru: 'Commissions and receivables/payables for remittances', uk: 'Commissions and receivables/payables for remittances', tr: 'Commissions and receivables/payables for remittances' },
  stg_remittance_commission_income   : { ar: 'إيرادات عمولات حوالات', en: 'Remittance Commission Income', ru: 'Remittance Commission Income', uk: 'Remittance Commission Income', tr: 'Remittance Commission Income' },
  stg_our_commission_per_remittance_ : { ar: 'عمولتنا من كل حوالة صادرة/واردة (432)', en: 'Our commission per remittance (432)', ru: 'Our commission per remittance (432)', uk: 'Our commission per remittance (432)', tr: 'Our commission per remittance (432)' },
  stg_remittances_payable            : { ar: 'حوالات مستحقة للتسليم', en: 'Remittances Payable', ru: 'Remittances Payable', uk: 'Remittances Payable', tr: 'Remittances Payable' },
  stg_our_obligation_to_deliver_remi : { ar: 'التزامنا بتسليم حوالات للمستقبلين (231)', en: 'Our obligation to deliver remittances (231)', ru: 'Our obligation to deliver remittances (231)', uk: 'Our obligation to deliver remittances (231)', tr: 'Our obligation to deliver remittances (231)' },
  stg_outgoing_remittance_receivable : { ar: 'ذمم حوالات صادرة', en: 'Outgoing Remittance Receivables', ru: 'Outgoing Remittance Receivables', uk: 'Outgoing Remittance Receivables', tr: 'Outgoing Remittance Receivables' },
  stg_remittance_amounts_awaiting_co : { ar: 'مبالغ حوالات ننتظر تحصيلها من الشريك/الوكيل (131)', en: 'Remittance amounts awaiting collection (131)', ru: 'Remittance amounts awaiting collection (131)', uk: 'Remittance amounts awaiting collection (131)', tr: 'Remittance amounts awaiting collection (131)' },
  stg_agent_partner_accounts         : { ar: 'حسابات الوكلاء والشركاء', en: 'Agent & Partner Accounts', ru: 'Agent & Partner Accounts', uk: 'Agent & Partner Accounts', tr: 'Agent & Partner Accounts' },
  stg_mutual_receivables_and_payable : { ar: 'الذمم والالتزامات المتبادلة مع الوكلاء والشركاء', en: 'Mutual receivables and payables with agents and partners', ru: 'Mutual receivables and payables with agents and partners', uk: 'Mutual receivables and payables with agents and partners', tr: 'Mutual receivables and payables with agents and partners' },
  stg_agents_payable                 : { ar: 'ذمم الوكلاء الدائنة', en: 'Agents Payable', ru: 'Agents Payable', uk: 'Agents Payable', tr: 'Agents Payable' },
  stg_amounts_we_owe_to_agents_232   : { ar: 'مبالغ مستحقة عليّنا للوكلاء (232)', en: 'Amounts we owe to agents (232)', ru: 'Amounts we owe to agents (232)', uk: 'Amounts we owe to agents (232)', tr: 'Amounts we owe to agents (232)' },
  stg_partners_payable               : { ar: 'ذمم الشركاء الدائنة', en: 'Partners Payable', ru: 'Partners Payable', uk: 'Partners Payable', tr: 'Partners Payable' },
  stg_partner_current_accounts_233   : { ar: 'ذمم الشركاء الدائنة — حسابات جارية (233)', en: 'Partner current accounts (233)', ru: 'Partner current accounts (233)', uk: 'Partner current accounts (233)', tr: 'Partner current accounts (233)' },
  stg_auto_post_exchange             : { ar: 'الترحيل التلقائي — الصرافة', en: 'Auto-Post — Exchange', ru: 'Auto-Post — Exchange', uk: 'Auto-Post — Exchange', tr: 'Auto-Post — Exchange' },
  stg_auto_post_exchange_operations  : { ar: 'ترحيل تلقائي — عمليات الصرف', en: 'Auto-post exchange operations', ru: 'Auto-post exchange operations', uk: 'Auto-post exchange operations', tr: 'Auto-post exchange operations' },
  stg_auto_post_entry_when_exchange_ : { ar: 'ترحيل القيد تلقائياً عند إتمام عملية الصرف', en: 'Auto-post entry when exchange is completed', ru: 'Auto-post entry when exchange is completed', uk: 'Auto-post entry when exchange is completed', tr: 'Auto-post entry when exchange is completed' },
  stg_auto_post_remittances          : { ar: 'ترحيل تلقائي — الحوالات', en: 'Auto-post remittances', ru: 'Auto-post remittances', uk: 'Auto-post remittances', tr: 'Auto-post remittances' },
  stg_auto_post_entry_when_remittanc : { ar: 'ترحيل القيد تلقائياً عند حفظ الحوالة', en: 'Auto-post entry when remittance is saved', ru: 'Auto-post entry when remittance is saved', uk: 'Auto-post entry when remittance is saved', tr: 'Auto-post entry when remittance is saved' },
  stg_auto_post_fx_variances         : { ar: 'ترحيل تلقائي — فروقات العملات', en: 'Auto-post FX variances', ru: 'Auto-post FX variances', uk: 'Auto-post FX variances', tr: 'Auto-post FX variances' },
  stg_auto_post_currency_rate_differ : { ar: 'ترحيل فروقات أسعار العملات تلقائياً', en: 'Auto-post currency rate differences', ru: 'Auto-post currency rate differences', uk: 'Auto-post currency rate differences', tr: 'Auto-post currency rate differences' },
  stg_fiscal_years                   : { ar: 'السنوات المالية', en: 'Fiscal Years', ru: 'Fiscal Years', uk: 'Fiscal Years', tr: 'Fiscal Years' },
  stg_manage_fiscal_years_and_accoun : { ar: 'إدارة السنوات والفترات المحاسبية', en: 'Manage fiscal years and accounting periods', ru: 'Manage fiscal years and accounting periods', uk: 'Manage fiscal years and accounting periods', tr: 'Manage fiscal years and accounting periods' },
  stg_add_new_year                   : { ar: 'إضافة سنة جديدة', en: 'Add New Year', ru: 'Add New Year', uk: 'Add New Year', tr: 'Add New Year' },
  stg_no_fiscal_years                : { ar: 'لا توجد سنوات مالية', en: 'No Fiscal Years', ru: 'No Fiscal Years', uk: 'No Fiscal Years', tr: 'No Fiscal Years' },
  stg_no_fiscal_years_defined_yet_ad : { ar: 'لم يتم تعريف أي سنة مالية بعد. قم بإضافة سنة مالية جديدة.', en: 'No fiscal years defined yet. Add a new fiscal year.', ru: 'No fiscal years defined yet. Add a new fiscal year.', uk: 'No fiscal years defined yet. Add a new fiscal year.', tr: 'No fiscal years defined yet. Add a new fiscal year.' },
  stg_current                        : { ar: 'الحالية', en: 'Current', ru: 'Current', uk: 'Current', tr: 'Current' },
  stg_closed                         : { ar: 'مغلقة', en: 'Closed', ru: 'Closed', uk: 'Closed', tr: 'Closed' },
  stg_entry_numbering                : { ar: 'ترقيم القيود', en: 'Entry Numbering', ru: 'Entry Numbering', uk: 'Entry Numbering', tr: 'Entry Numbering' },
  stg_configure_journal_entry_number : { ar: 'تكوين نظام ترقيم القيود المحاسبية', en: 'Configure journal entry numbering system', ru: 'Configure journal entry numbering system', uk: 'Configure journal entry numbering system', tr: 'Configure journal entry numbering system' },
  stg_entry_number_prefix            : { ar: 'بادئة رقم القيد', en: 'Entry Number Prefix', ru: 'Entry Number Prefix', uk: 'Entry Number Prefix', tr: 'Entry Number Prefix' },
  stg_example_settings_journal_entry : { ar: 'مثال: ${settings.journal_entry_prefix}-2026-00001', en: 'Example: ${settings.journal_entry_prefix}-2026-00001', ru: 'Example: ${settings.journal_entry_prefix}-2026-00001', uk: 'Example: ${settings.journal_entry_prefix}-2026-00001', tr: 'Example: ${settings.journal_entry_prefix}-2026-00001' },
  stg_current_sequence               : { ar: 'الرقم التسلسلي الحالي', en: 'Current Sequence', ru: 'Current Sequence', uk: 'Current Sequence', tr: 'Current Sequence' },
  stg_reset_yearly                   : { ar: 'إعادة الترقيم سنوياً', en: 'Reset Yearly', ru: 'Reset Yearly', uk: 'Reset Yearly', tr: 'Reset Yearly' },
  stg_reset_numbering_to_1_at_the_st : { ar: 'إعادة الترقيم من 1 مع بداية كل سنة مالية', en: 'Reset numbering to 1 at the start of each fiscal year', ru: 'Reset numbering to 1 at the start of each fiscal year', uk: 'Reset numbering to 1 at the start of each fiscal year', tr: 'Reset numbering to 1 at the start of each fiscal year' },
  stg_current_format                 : { ar: 'التنسيق الحالي', en: 'Current Format', ru: 'Current Format', uk: 'Current Format', tr: 'Current Format' },
  stg_fiscal_year_management_mode    : { ar: 'نمط إدارة السنوات المالية', en: 'Fiscal Year Management Mode', ru: 'Fiscal Year Management Mode', uk: 'Fiscal Year Management Mode', tr: 'Fiscal Year Management Mode' },
  stg_choose_how_to_handle_closed_fi : { ar: 'اختر كيفية التعامل مع السنوات المالية المُغلقة', en: 'Choose how to handle closed fiscal years', ru: 'Choose how to handle closed fiscal years', uk: 'Choose how to handle closed fiscal years', tr: 'Choose how to handle closed fiscal years' },
  stg_independent_years              : { ar: 'السنوات المستقلة', en: 'Independent Years', ru: 'Independent Years', uk: 'Independent Years', tr: 'Independent Years' },
  stg_each_closed_fiscal_year_is_ind : { ar: 'كل سنة مالية مُغلقة تُعتبر مستقلة. يمكن التعديل على القيود بدون التأثير على السنوات اللاحقة.', en: 'Each closed fiscal year is independent. You can edit entries without affecting subsequent years.', ru: 'Each closed fiscal year is independent. You can edit entries without affecting subsequent years.', uk: 'Each closed fiscal year is independent. You can edit entries without affecting subsequent years.', tr: 'Each closed fiscal year is independent. You can edit entries without affecting subsequent years.' },
  stg_recommended_for_smbs           : { ar: '⚡ مُوصى به للشركات الصغيرة والمتوسطة', en: '⚡ Recommended for SMBs', ru: '⚡ Recommended for SMBs', uk: '⚡ Recommended for SMBs', tr: '⚡ Recommended for SMBs' },
  stg_linked_years                   : { ar: 'السنوات المترابطة', en: 'Linked Years', ru: 'Linked Years', uk: 'Linked Years', tr: 'Linked Years' },
  stg_fiscal_years_are_linked_cannot : { ar: 'السنوات المالية مُرتبطة. لا يمكن تعديل السنوات المُغلقة. التصحيح يتم بقيد تسوية في السنة الحالية.', en: 'Fiscal years are linked. Cannot edit closed years. Corrections require adjustment entries in current year.', ru: 'Fiscal years are linked. Cannot edit closed years. Corrections require adjustment entries in current year.', uk: 'Fiscal years are linked. Cannot edit closed years. Corrections require adjustment entries in current year.', tr: 'Fiscal years are linked. Cannot edit closed years. Corrections require adjustment entries in current year.' },
  stg_recommended_for_large_regulate : { ar: '🏢 مُوصى به للشركات الكبيرة والمُلزمة ضريبياً', en: '🏢 Recommended for large/regulated companies', ru: '🏢 Recommended for large/regulated companies', uk: '🏢 Recommended for large/regulated companies', tr: '🏢 Recommended for large/regulated companies' },
  stg_edit_settings                  : { ar: 'إعدادات التعديل', en: 'Edit Settings', ru: 'Edit Settings', uk: 'Edit Settings', tr: 'Edit Settings' },
  stg_control_how_posted_entries_can : { ar: 'تحكم في طريقة التعديل على القيود المُرحلة', en: 'Control how posted entries can be edited', ru: 'Control how posted entries can be edited', uk: 'Control how posted entries can be edited', tr: 'Control how posted entries can be edited' },
  stg_allow_direct_edit_on_posted_en : { ar: 'السماح بالتعديل المباشر على القيود المُرحلة', en: 'Allow direct edit on posted entries', ru: 'Allow direct edit on posted entries', uk: 'Allow direct edit on posted entries', tr: 'Allow direct edit on posted entries' },
  stg_system_auto_unposts_edits_then : { ar: 'النظام يُلغي الترحيل تلقائياً للتعديل ثم يُعيد الترحيل', en: 'System auto-unposts, edits, then re-posts', ru: 'System auto-unposts, edits, then re-posts', uk: 'System auto-unposts, edits, then re-posts', tr: 'System auto-unposts, edits, then re-posts' },
  stg_auto_re_post_after_save        : { ar: 'إعادة الترحيل تلقائياً بعد الحفظ', en: 'Auto re-post after save', ru: 'Auto re-post after save', uk: 'Auto re-post after save', tr: 'Auto re-post after save' },
  stg_automatically_post_entry_after : { ar: 'ترحيل القيد تلقائياً بعد حفظ التعديلات', en: 'Automatically post entry after saving edits', ru: 'Automatically post entry after saving edits', uk: 'Automatically post entry after saving edits', tr: 'Automatically post entry after saving edits' },
  stg_require_edit_reason            : { ar: 'طلب سبب للتعديل', en: 'Require edit reason', ru: 'Require edit reason', uk: 'Require edit reason', tr: 'Require edit reason' },
  stg_require_user_to_enter_a_reason : { ar: 'إلزام المستخدم بإدخال سبب عند التعديل', en: 'Require user to enter a reason when editing', ru: 'Require user to enter a reason when editing', uk: 'Require user to enter a reason when editing', tr: 'Require user to enter a reason when editing' },
  stg_notify_on_posted_edit          : { ar: 'إشعار عند التعديل على المُرحل', en: 'Notify on posted edit', ru: 'Notify on posted edit', uk: 'Notify on posted edit', tr: 'Notify on posted edit' },
  stg_send_notification_when_editing : { ar: 'إرسال إشعار عند التعديل على قيد مُرحل', en: 'Send notification when editing posted entries', ru: 'Send notification when editing posted entries', uk: 'Send notification when editing posted entries', tr: 'Send notification when editing posted entries' },
  stg_closed_year_settings           : { ar: 'إعدادات السنوات المُغلقة', en: 'Closed Year Settings', ru: 'Closed Year Settings', uk: 'Closed Year Settings', tr: 'Closed Year Settings' },
  stg_control_edit_permissions_for_c : { ar: 'تحكم في صلاحيات التعديل على السنوات المالية المُغلقة (النظام المستقل)', en: 'Control edit permissions for closed fiscal years (Independent mode)', ru: 'Control edit permissions for closed fiscal years (Independent mode)', uk: 'Control edit permissions for closed fiscal years (Independent mode)', tr: 'Control edit permissions for closed fiscal years (Independent mode)' },
  stg_allow_edit_on_closed_years     : { ar: 'السماح بالتعديل على السنوات المُغلقة', en: 'Allow edit on closed years', ru: 'Allow edit on closed years', uk: 'Allow edit on closed years', tr: 'Allow edit on closed years' },
  stg_edits_will_not_affect_opening_ : { ar: '⚠️ التعديلات لن تؤثر على الأرصدة الافتتاحية للسنوات اللاحقة', en: '⚠️ Edits will not affect opening balances of subsequent years', ru: '⚠️ Edits will not affect opening balances of subsequent years', uk: '⚠️ Edits will not affect opening balances of subsequent years', tr: '⚠️ Edits will not affect opening balances of subsequent years' },
  stg_allow_delete_in_closed_years   : { ar: 'السماح بالحذف في السنوات المُغلقة', en: 'Allow delete in closed years', ru: 'Allow delete in closed years', uk: 'Allow delete in closed years', tr: 'Allow delete in closed years' },
  stg_not_recommended_deletions_are_ : { ar: '❌ غير مُوصى به - الحذف يُسجّل في Audit Log', en: '❌ Not recommended - Deletions are logged in Audit', ru: '❌ Not recommended - Deletions are logged in Audit', uk: '❌ Not recommended - Deletions are logged in Audit', tr: '❌ Not recommended - Deletions are logged in Audit' },
  stg_link_adjustment_entries_to_ori : { ar: 'ربط قيود التسوية بالقيود الأصلية', en: 'Link adjustment entries to originals', ru: 'Link adjustment entries to originals', uk: 'Link adjustment entries to originals', tr: 'Link adjustment entries to originals' },
  stg_create_a_link_between_adjustme : { ar: 'إنشاء رابط بين قيد التسوية والقيد الأصلي', en: 'Create a link between adjustment and original entry', ru: 'Create a link between adjustment and original entry', uk: 'Create a link between adjustment and original entry', tr: 'Create a link between adjustment and original entry' },
  stg_linked_years_mode              : { ar: 'نظام السنوات المترابطة', en: 'Linked Years Mode', ru: 'Linked Years Mode', uk: 'Linked Years Mode', tr: 'Linked Years Mode' },
  stg_in_this_mode_closed_fiscal_yea : { ar: 'في هذا النظام، لا يمكن التعديل على السنوات المالية المُغلقة. أي تصحيحات يجب أن تتم عبر قيد تسوية في السنة المالية الحالية، مرتبط بالقيد الأصلي.', en: 'In this mode, closed fiscal years cannot be edited. Any corrections must be made through an adjustment entry in the current fiscal year, linked to the original entry.', ru: 'In this mode, closed fiscal years cannot be edited. Any corrections must be made through an adjustment entry in the current fiscal year, linked to the original entry.', uk: 'In this mode, closed fiscal years cannot be edited. Any corrections must be made through an adjustment entry in the current fiscal year, linked to the original entry.', tr: 'In this mode, closed fiscal years cannot be edited. Any corrections must be made through an adjustment entry in the current fiscal year, linked to the original entry.' },
  stg_notifications                  : { ar: 'الإشعارات', en: 'Notifications', ru: 'Notifications', uk: 'Notifications', tr: 'Notifications' },
  stg_notify_cfo_on_closed_year_edit : { ar: 'إشعار المدير المالي عند التعديل على سنة مُغلقة', en: 'Notify CFO on closed year edit', ru: 'Notify CFO on closed year edit', uk: 'Notify CFO on closed year edit', tr: 'Notify CFO on closed year edit' },
  stg_send_notification_to_cfo       : { ar: 'إرسال إشعار للمدير المالي', en: 'Send notification to CFO', ru: 'Send notification to CFO', uk: 'Send notification to CFO', tr: 'Send notification to CFO' },
  stg_notify_on_large_adjustments    : { ar: 'إشعار عند التسويات الكبيرة', en: 'Notify on large adjustments', ru: 'Notify on large adjustments', uk: 'Notify on large adjustments', tr: 'Notify on large adjustments' },
  stg_value_greater_than_editsetting : { ar: 'قيمة أكبر من ${editSettings.notifications.large_adjustment_threshold.toLocaleString()}', en: 'Value greater than ${editSettings.notifications.large_adjustment_threshold.toLocaleString()}', ru: 'Value greater than ${editSettings.notifications.large_adjustment_threshold.toLocaleString()}', uk: 'Value greater than ${editSettings.notifications.large_adjustment_threshold.toLocaleString()}', tr: 'Value greater than ${editSettings.notifications.large_adjustment_threshold.toLocaleString()}' },
  stg_large_adjustment_threshold     : { ar: 'حد التسوية الكبيرة', en: 'Large Adjustment Threshold', ru: 'Large Adjustment Threshold', uk: 'Large Adjustment Threshold', tr: 'Large Adjustment Threshold' },
  stg_cost_center_management         : { ar: 'إدارة مراكز التكلفة', en: 'Cost Center Management', ru: 'Cost Center Management', uk: 'Cost Center Management', tr: 'Cost Center Management' },
  stg_add_edit_and_delete_cost_cente : { ar: 'إضافة وتعديل وحذف مراكز التكلفة المستخدمة في القيود اليومية', en: 'Add, edit and delete cost centers used in journal entries', ru: 'Add, edit and delete cost centers used in journal entries', uk: 'Add, edit and delete cost centers used in journal entries', tr: 'Add, edit and delete cost centers used in journal entries' },
  stg_add                            : { ar: 'إضافة', en: 'Add', ru: 'Add', uk: 'Add', tr: 'Add' },
  stg_code                           : { ar: 'الرمز', en: 'Code', ru: 'Code', uk: 'Code', tr: 'Code' },
  stg_name_arabic                    : { ar: 'الاسم بالعربية', en: 'Name (Arabic)', ru: 'Name (Arabic)', uk: 'Name (Arabic)', tr: 'Name (Arabic)' },
  stg_name_english                   : { ar: 'الاسم بالإنجليزية', en: 'Name (English)', ru: 'Name (English)', uk: 'Name (English)', tr: 'Name (English)' },
  stg_added                          : { ar: 'تمت الإضافة', en: 'Added', ru: 'Added', uk: 'Added', tr: 'Added' },
  stg_arabic_name                    : { ar: 'الاسم بالعربية', en: 'Arabic Name', ru: 'Arabic Name', uk: 'Arabic Name', tr: 'Arabic Name' },
  stg_english_name                   : { ar: 'الاسم بالإنجليزية', en: 'English Name', ru: 'English Name', uk: 'English Name', tr: 'English Name' },
  stg_status                         : { ar: 'الحالة', en: 'Status', ru: 'Status', uk: 'Status', tr: 'Status' },
  stg_actions                        : { ar: 'إجراءات', en: 'Actions', ru: 'Actions', uk: 'Actions', tr: 'Actions' },
  stg_no_cost_centers_click_add_to_c : { ar: 'لا توجد مراكز تكلفة. اضغط "إضافة" لإنشاء مركز تكلفة جديد.', en: 'No cost centers. Click "Add" to create one.', ru: 'No cost centers. Click "Add" to create one.', uk: 'No cost centers. Click "Add" to create one.', tr: 'No cost centers. Click "Add" to create one.' },
  stg_updated                        : { ar: 'تم التحديث', en: 'Updated', ru: 'Updated', uk: 'Updated', tr: 'Updated' },
  stg_active                         : { ar: 'نشط', en: 'Active', ru: 'Active', uk: 'Active', tr: 'Active' },
  stg_inactive                       : { ar: 'معطل', en: 'Inactive', ru: 'Inactive', uk: 'Inactive', tr: 'Inactive' },
  stg_are_you_sure                   : { ar: 'هل أنت متأكد من الحذف؟', en: 'Are you sure?', ru: 'Are you sure?', uk: 'Are you sure?', tr: 'Are you sure?' },
  stg_deleted                        : { ar: 'تم الحذف', en: 'Deleted', ru: 'Deleted', uk: 'Deleted', tr: 'Deleted' },
  stg_total_cost_centers_costcenters : { ar: 'إجمالي مراكز التكلفة: ${costCentersList.length}', en: 'Total cost centers: ${costCentersList.length}', ru: 'Total cost centers: ${costCentersList.length}', uk: 'Total cost centers: ${costCentersList.length}', tr: 'Total cost centers: ${costCentersList.length}' },
  stg_saving                         : { ar: 'جاري الحفظ...', en: 'Saving...', ru: 'Saving...', uk: 'Saving...', tr: 'Saving...' },
  stg_save_settings                  : { ar: 'حفظ الإعدادات', en: 'Save Settings', ru: 'Save Settings', uk: 'Save Settings', tr: 'Save Settings' },
};

/**
 * Get a common warehouse label in the user's language.
 */
export function getLocalizedLabel(key: string, language: string): string {
  const entry = LABELS[key];
  if (!entry) return key;
  return entry[language] || entry.en || key;
}
