-- ═══════════════════════════════════════════════════════════════════════════
-- 🔍 فحص الجداول غير المصنفة (Other)
-- ═══════════════════════════════════════════════════════════════════════════

SELECT 
    tablename as "الجدول",
    (SELECT n_live_tup FROM pg_stat_user_tables s WHERE s.relname = t.tablename) as "الصفوف"
FROM pg_tables t
WHERE schemaname = 'public'
AND tablename NOT LIKE '%tenant%' 
AND tablename NOT LIKE '%brand%' 
AND tablename NOT LIKE '%subscription%'
AND tablename NOT LIKE '%user%' 
AND tablename NOT LIKE '%role%' 
AND tablename NOT LIKE '%permission%' 
AND tablename NOT LIKE '%mfa%' 
AND tablename NOT LIKE '%auth%'
AND tablename NOT LIKE '%compan%' 
AND tablename NOT LIKE '%branch%'
AND tablename NOT LIKE '%account%' 
AND tablename NOT LIKE '%journal%' 
AND tablename NOT LIKE '%ledger%' 
AND tablename NOT LIKE '%fiscal%' 
AND tablename NOT LIKE '%cost_center%'
AND tablename NOT LIKE '%warehouse%' 
AND tablename NOT LIKE '%inventor%' 
AND tablename NOT LIKE '%stock%' 
AND tablename NOT LIKE '%location%' 
AND tablename NOT LIKE '%roll%' 
AND tablename NOT LIKE '%fabric%' 
AND tablename NOT LIKE '%batch%'
AND tablename NOT LIKE '%product%' 
AND tablename NOT LIKE '%item%' 
AND tablename NOT LIKE '%categor%' 
AND tablename NOT LIKE '%unit%'
AND tablename NOT LIKE '%sale%' 
AND tablename NOT LIKE '%invoice%' 
AND tablename NOT LIKE '%customer%' 
AND tablename NOT LIKE '%order%' 
AND tablename NOT LIKE '%quotation%'
AND tablename NOT LIKE '%purchase%' 
AND tablename NOT LIKE '%supplier%' 
AND tablename NOT LIKE '%vendor%'
AND tablename NOT LIKE '%employee%' 
AND tablename NOT LIKE '%payroll%' 
AND tablename NOT LIKE '%attendance%' 
AND tablename NOT LIKE '%leave%' 
AND tablename NOT LIKE '%salary%'
AND tablename NOT LIKE '%bank%' 
AND tablename NOT LIKE '%cash%' 
AND tablename NOT LIKE '%payment%' 
AND tablename NOT LIKE '%receipt%' 
AND tablename NOT LIKE '%treasury%'
AND tablename NOT LIKE '%currenc%' 
AND tablename NOT LIKE '%exchange%'
AND tablename NOT LIKE '%audit%' 
AND tablename NOT LIKE '%log%' 
AND tablename NOT LIKE '%history%'
AND tablename NOT LIKE '%setting%' 
AND tablename NOT LIKE '%config%' 
AND tablename NOT LIKE '%preference%'
AND tablename NOT LIKE '%document%' 
AND tablename NOT LIKE '%attachment%' 
AND tablename NOT LIKE '%file%'
ORDER BY tablename;
