[click-to-call-context]
exten => 700,1,NoOp(WebRTC Guest from ${CHANNEL(peerip)})
same  =>     n,Set(GROUP()=webrtc-guests)
same  =>     n,GotoIf($[${GROUP_COUNT(webrtc-guests)} > 10]?spam)
same  =>     n,Answer()
same  =>     n,Wait(0.5)
same  =>     n,Dial(PJSIP/100,60,m(texacore-ivr))
same  =>     n,Hangup()

exten => _X.,1,Hangup(CALL_REJECTED)
exten => _X.,n(spam),Playback(all-circuits-busy-now)
same  =>     n,Hangup(INTERWORKING)
exten => i,1,Hangup(CALL_REJECTED)
exten => t,1,Hangup(NORMAL_CLEARING)
exten => h,1,NoOp(Call ended)
