version: '3'
services:
  meshcentral:
    image: typhonragewind/meshcentral:latest
    container_name: texacore-mdm
    restart: always
    environment:
      - HOSTNAME=mdm.texacore.local # Change this to your actual subdomain later
      - REVERSE_PROXY=true # We need this for Cloudflare Tunnels
      - REVERSE_PROXY_TLS_PORT=443
      - IFRAME_ANY=true
      - ALLOW_NEW_ACCOUNTS=true
    ports:
      - "8080:443" # Exposing HTTPS port locally
    volumes:
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./meshcentral/files:/opt/meshcentral/meshcentral-files
