#!/usr/bin/env node

/**
 * 🌍 Texa Core - Batch Translation Fix
 * Replaces placeholder translations with proper translations
 */

const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, '../src/i18n/locales');

// Common translations mapping
const translations = {
  // German (DE)
  de: {
    // Common actions
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'edit': 'Bearbeiten',
    'add': 'Hinzufügen',
    'create': 'Erstellen',
    'update': 'Aktualisieren',
    'search': 'Suchen',
    'filter': 'Filtern',
    'export': 'Exportieren',
    'import': 'Importieren',
    'print': 'Drucken',
    'download': 'Herunterladen',
    'upload': 'Hochladen',
    'close': 'Schließen',
    'back': 'Zurück',
    'next': 'Weiter',
    'previous': 'Vorherige',
    'submit': 'Absenden',
    'confirm': 'Bestätigen',
    'yes': 'Ja',
    'no': 'Nein',
    'ok': 'OK',
    'loading': 'Laden...',
    'processing': 'Verarbeitung...',
    'error': 'Fehler',
    'success': 'Erfolg',
    'warning': 'Warnung',
    'info': 'Information',
    'details': 'Details',
    'overview': 'Übersicht',
    'settings': 'Einstellungen',
    'options': 'Optionen',
    'actions': 'Aktionen',
    'status': 'Status',
    'active': 'Aktiv',
    'inactive': 'Inaktiv',
    'pending': 'Ausstehend',
    'completed': 'Abgeschlossen',
    'cancelled': 'Storniert',
    'draft': 'Entwurf',
    'name': 'Name',
    'description': 'Beschreibung',
    'date': 'Datum',
    'time': 'Zeit',
    'amount': 'Betrag',
    'total': 'Gesamt',
    'balance': 'Saldo',
    'price': 'Preis',
    'quantity': 'Menge',
    'type': 'Typ',
    'category': 'Kategorie',
    'notes': 'Notizen',
    'comments': 'Kommentare',
    'email': 'E-Mail',
    'phone': 'Telefon',
    'address': 'Adresse',
    'city': 'Stadt',
    'country': 'Land',
    'or': 'oder',
    'and': 'und',
    'all': 'Alle',
    'none': 'Keine',
    'select': 'Auswählen',
    'selected': 'Ausgewählt',
    'required': 'Erforderlich',
    'optional': 'Optional',
    'new': 'Neu',
    'view': 'Ansehen',
    'more': 'Mehr',
    'less': 'Weniger',
    'show': 'Anzeigen',
    'hide': 'Verbergen',
    'copy': 'Kopieren',
    'paste': 'Einfügen',
    'cut': 'Ausschneiden',
    'undo': 'Rückgängig',
    'redo': 'Wiederholen',
    'refresh': 'Aktualisieren',
    'reset': 'Zurücksetzen',
    'clear': 'Löschen',
    'apply': 'Anwenden',
    'done': 'Fertig',
    
    // Dashboard
    'Active Customers': 'Aktive Kunden',
    'Completed Orders': 'Abgeschlossene Bestellungen',
    'Gross Profit': 'Bruttogewinn',
    'Low Stock': 'Niedriger Bestand',
    'Net Profit': 'Nettogewinn',
    'New Customers': 'Neue Kunden',
    'Out of Stock': 'Nicht vorrätig',
    'Pending Orders': 'Ausstehende Bestellungen',
    'Total Customers': 'Gesamtkunden',
    'Total Expenses': 'Gesamtausgaben',
    'Total Orders': 'Gesamtbestellungen',
    'Total Products': 'Gesamtprodukte',
    'Total Revenue': 'Gesamtumsatz',
    'Total Suppliers': 'Gesamtlieferanten',
    
    // Accounting
    'accounts': 'Konten',
    'account': 'Konto',
    'journal': 'Journal',
    'ledger': 'Hauptbuch',
    'invoice': 'Rechnung',
    'invoices': 'Rechnungen',
    'payment': 'Zahlung',
    'payments': 'Zahlungen',
    'receipt': 'Quittung',
    'receipts': 'Quittungen',
    'transaction': 'Transaktion',
    'transactions': 'Transaktionen',
    'debit': 'Soll',
    'credit': 'Haben',
    'assets': 'Vermögenswerte',
    'liabilities': 'Verbindlichkeiten',
    'equity': 'Eigenkapital',
    'revenue': 'Umsatz',
    'expenses': 'Ausgaben',
    'profit': 'Gewinn',
    'loss': 'Verlust',
    'tax': 'Steuer',
    'vat': 'MwSt.',
    'currency': 'Währung',
  },
  
  // Turkish (TR)
  tr: {
    'save': 'Kaydet',
    'cancel': 'İptal',
    'delete': 'Sil',
    'edit': 'Düzenle',
    'add': 'Ekle',
    'create': 'Oluştur',
    'update': 'Güncelle',
    'search': 'Ara',
    'filter': 'Filtrele',
    'export': 'Dışa Aktar',
    'import': 'İçe Aktar',
    'print': 'Yazdır',
    'download': 'İndir',
    'upload': 'Yükle',
    'close': 'Kapat',
    'back': 'Geri',
    'next': 'İleri',
    'previous': 'Önceki',
    'submit': 'Gönder',
    'confirm': 'Onayla',
    'yes': 'Evet',
    'no': 'Hayır',
    'ok': 'Tamam',
    'loading': 'Yükleniyor...',
    'processing': 'İşleniyor...',
    'error': 'Hata',
    'success': 'Başarılı',
    'warning': 'Uyarı',
    'info': 'Bilgi',
    'details': 'Detaylar',
    'overview': 'Genel Bakış',
    'settings': 'Ayarlar',
    'options': 'Seçenekler',
    'actions': 'İşlemler',
    'status': 'Durum',
    'active': 'Aktif',
    'inactive': 'Pasif',
    'pending': 'Beklemede',
    'completed': 'Tamamlandı',
    'cancelled': 'İptal Edildi',
    'draft': 'Taslak',
    'name': 'Ad',
    'description': 'Açıklama',
    'date': 'Tarih',
    'time': 'Zaman',
    'amount': 'Tutar',
    'total': 'Toplam',
    'balance': 'Bakiye',
    'price': 'Fiyat',
    'quantity': 'Miktar',
    'type': 'Tür',
    'category': 'Kategori',
    'notes': 'Notlar',
    'email': 'E-posta',
    'phone': 'Telefon',
    'address': 'Adres',
    'city': 'Şehir',
    'country': 'Ülke',
    'or': 'veya',
    'and': 've',
    'all': 'Tümü',
    'none': 'Hiçbiri',
    'select': 'Seç',
    'required': 'Zorunlu',
    'optional': 'İsteğe Bağlı',
    
    // Dashboard
    'Active Customers': 'Aktif Müşteriler',
    'Completed Orders': 'Tamamlanan Siparişler',
    'Gross Profit': 'Brüt Kar',
    'Low Stock': 'Düşük Stok',
    'Net Profit': 'Net Kar',
    'New Customers': 'Yeni Müşteriler',
    'Out of Stock': 'Stok Yok',
    'Pending Orders': 'Bekleyen Siparişler',
    'Total Customers': 'Toplam Müşteri',
    'Total Expenses': 'Toplam Giderler',
    'Total Orders': 'Toplam Sipariş',
    'Total Products': 'Toplam Ürün',
    'Total Revenue': 'Toplam Gelir',
    'Total Suppliers': 'Toplam Tedarikçi',
    
    // Accounting
    'accounts': 'Hesaplar',
    'account': 'Hesap',
    'journal': 'Yevmiye',
    'ledger': 'Defter',
    'invoice': 'Fatura',
    'invoices': 'Faturalar',
    'payment': 'Ödeme',
    'payments': 'Ödemeler',
    'receipt': 'Makbuz',
    'debit': 'Borç',
    'credit': 'Alacak',
    'assets': 'Varlıklar',
    'liabilities': 'Borçlar',
    'equity': 'Özkaynak',
    'revenue': 'Gelir',
    'expenses': 'Giderler',
    'profit': 'Kar',
    'loss': 'Zarar',
    'tax': 'Vergi',
    'currency': 'Para Birimi',
  },
  
  // Russian (RU)
  ru: {
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Редактировать',
    'add': 'Добавить',
    'create': 'Создать',
    'update': 'Обновить',
    'search': 'Поиск',
    'filter': 'Фильтр',
    'export': 'Экспорт',
    'import': 'Импорт',
    'print': 'Печать',
    'download': 'Скачать',
    'upload': 'Загрузить',
    'close': 'Закрыть',
    'back': 'Назад',
    'next': 'Далее',
    'previous': 'Предыдущий',
    'submit': 'Отправить',
    'confirm': 'Подтвердить',
    'yes': 'Да',
    'no': 'Нет',
    'ok': 'ОК',
    'loading': 'Загрузка...',
    'processing': 'Обработка...',
    'error': 'Ошибка',
    'success': 'Успех',
    'warning': 'Предупреждение',
    'info': 'Информация',
    'details': 'Детали',
    'overview': 'Обзор',
    'settings': 'Настройки',
    'options': 'Опции',
    'actions': 'Действия',
    'status': 'Статус',
    'active': 'Активный',
    'inactive': 'Неактивный',
    'pending': 'Ожидание',
    'completed': 'Завершено',
    'cancelled': 'Отменено',
    'draft': 'Черновик',
    'name': 'Название',
    'description': 'Описание',
    'date': 'Дата',
    'time': 'Время',
    'amount': 'Сумма',
    'total': 'Итого',
    'balance': 'Баланс',
    'price': 'Цена',
    'quantity': 'Количество',
    'type': 'Тип',
    'category': 'Категория',
    'notes': 'Заметки',
    'email': 'Эл. почта',
    'phone': 'Телефон',
    'address': 'Адрес',
    'city': 'Город',
    'country': 'Страна',
    'or': 'или',
    'and': 'и',
    'all': 'Все',
    'none': 'Нет',
    'select': 'Выбрать',
    'required': 'Обязательно',
    'optional': 'Необязательно',
    
    // Dashboard
    'Active Customers': 'Активные клиенты',
    'Completed Orders': 'Выполненные заказы',
    'Gross Profit': 'Валовая прибыль',
    'Low Stock': 'Низкий запас',
    'Net Profit': 'Чистая прибыль',
    'New Customers': 'Новые клиенты',
    'Out of Stock': 'Нет в наличии',
    'Pending Orders': 'Ожидающие заказы',
    'Total Customers': 'Всего клиентов',
    'Total Expenses': 'Всего расходов',
    'Total Orders': 'Всего заказов',
    'Total Products': 'Всего товаров',
    'Total Revenue': 'Общий доход',
    'Total Suppliers': 'Всего поставщиков',
    
    // Accounting
    'accounts': 'Счета',
    'account': 'Счет',
    'journal': 'Журнал',
    'ledger': 'Книга учета',
    'invoice': 'Счет-фактура',
    'invoices': 'Счета-фактуры',
    'payment': 'Платеж',
    'payments': 'Платежи',
    'receipt': 'Квитанция',
    'debit': 'Дебет',
    'credit': 'Кредит',
    'assets': 'Активы',
    'liabilities': 'Обязательства',
    'equity': 'Капитал',
    'revenue': 'Доход',
    'expenses': 'Расходы',
    'profit': 'Прибыль',
    'loss': 'Убыток',
    'tax': 'Налог',
    'currency': 'Валюта',
  },
  
  // Ukrainian (UK)
  uk: {
    'save': 'Зберегти',
    'cancel': 'Скасувати',
    'delete': 'Видалити',
    'edit': 'Редагувати',
    'add': 'Додати',
    'create': 'Створити',
    'update': 'Оновити',
    'search': 'Пошук',
    'filter': 'Фільтр',
    'export': 'Експорт',
    'import': 'Імпорт',
    'print': 'Друк',
    'download': 'Завантажити',
    'close': 'Закрити',
    'back': 'Назад',
    'next': 'Далі',
    'yes': 'Так',
    'no': 'Ні',
    'ok': 'ОК',
    'loading': 'Завантаження...',
    'error': 'Помилка',
    'success': 'Успіх',
    'warning': 'Попередження',
    'details': 'Деталі',
    'overview': 'Огляд',
    'settings': 'Налаштування',
    'status': 'Статус',
    'active': 'Активний',
    'inactive': 'Неактивний',
    'pending': 'Очікування',
    'completed': 'Завершено',
    'name': 'Назва',
    'description': 'Опис',
    'date': 'Дата',
    'amount': 'Сума',
    'total': 'Всього',
    'balance': 'Баланс',
    'price': 'Ціна',
    'quantity': 'Кількість',
    'type': 'Тип',
    'category': 'Категорія',
    'notes': 'Нотатки',
    'email': 'Ел. пошта',
    'phone': 'Телефон',
    'address': 'Адреса',
    'or': 'або',
    'all': 'Все',
    
    // Dashboard
    'Active Customers': 'Активні клієнти',
    'Completed Orders': 'Виконані замовлення',
    'Gross Profit': 'Валовий прибуток',
    'Low Stock': 'Низький запас',
    'Net Profit': 'Чистий прибуток',
    'New Customers': 'Нові клієнти',
    'Out of Stock': 'Немає в наявності',
    'Pending Orders': 'Очікувані замовлення',
    'Total Customers': 'Всього клієнтів',
    'Total Expenses': 'Всього витрат',
    'Total Orders': 'Всього замовлень',
    'Total Products': 'Всього товарів',
    'Total Revenue': 'Загальний дохід',
    'Total Suppliers': 'Всього постачальників',
  },
  
  // Italian (IT)
  it: {
    'save': 'Salva',
    'cancel': 'Annulla',
    'delete': 'Elimina',
    'edit': 'Modifica',
    'add': 'Aggiungi',
    'create': 'Crea',
    'update': 'Aggiorna',
    'search': 'Cerca',
    'filter': 'Filtra',
    'export': 'Esporta',
    'import': 'Importa',
    'print': 'Stampa',
    'download': 'Scarica',
    'close': 'Chiudi',
    'back': 'Indietro',
    'next': 'Avanti',
    'yes': 'Sì',
    'no': 'No',
    'ok': 'OK',
    'loading': 'Caricamento...',
    'error': 'Errore',
    'success': 'Successo',
    'warning': 'Avviso',
    'details': 'Dettagli',
    'overview': 'Panoramica',
    'settings': 'Impostazioni',
    'status': 'Stato',
    'active': 'Attivo',
    'inactive': 'Inattivo',
    'pending': 'In attesa',
    'completed': 'Completato',
    'name': 'Nome',
    'description': 'Descrizione',
    'date': 'Data',
    'amount': 'Importo',
    'total': 'Totale',
    'balance': 'Saldo',
    'price': 'Prezzo',
    'quantity': 'Quantità',
    'type': 'Tipo',
    'category': 'Categoria',
    'notes': 'Note',
    'email': 'E-mail',
    'phone': 'Telefono',
    'address': 'Indirizzo',
    'or': 'o',
    'all': 'Tutti',
    
    // Dashboard
    'Active Customers': 'Clienti attivi',
    'Completed Orders': 'Ordini completati',
    'Gross Profit': 'Profitto lordo',
    'Low Stock': 'Stock basso',
    'Net Profit': 'Profitto netto',
    'New Customers': 'Nuovi clienti',
    'Out of Stock': 'Esaurito',
    'Pending Orders': 'Ordini in sospeso',
    'Total Customers': 'Clienti totali',
    'Total Expenses': 'Spese totali',
    'Total Orders': 'Ordini totali',
    'Total Products': 'Prodotti totali',
    'Total Revenue': 'Ricavi totali',
    'Total Suppliers': 'Fornitori totali',
  },
  
  // Polish (PL)
  pl: {
    'save': 'Zapisz',
    'cancel': 'Anuluj',
    'delete': 'Usuń',
    'edit': 'Edytuj',
    'add': 'Dodaj',
    'create': 'Utwórz',
    'update': 'Aktualizuj',
    'search': 'Szukaj',
    'filter': 'Filtruj',
    'export': 'Eksportuj',
    'import': 'Importuj',
    'print': 'Drukuj',
    'download': 'Pobierz',
    'close': 'Zamknij',
    'back': 'Wstecz',
    'next': 'Dalej',
    'yes': 'Tak',
    'no': 'Nie',
    'ok': 'OK',
    'loading': 'Ładowanie...',
    'error': 'Błąd',
    'success': 'Sukces',
    'warning': 'Ostrzeżenie',
    'details': 'Szczegóły',
    'overview': 'Przegląd',
    'settings': 'Ustawienia',
    'status': 'Status',
    'active': 'Aktywny',
    'inactive': 'Nieaktywny',
    'pending': 'Oczekujący',
    'completed': 'Ukończono',
    'name': 'Nazwa',
    'description': 'Opis',
    'date': 'Data',
    'amount': 'Kwota',
    'total': 'Suma',
    'balance': 'Saldo',
    'price': 'Cena',
    'quantity': 'Ilość',
    'type': 'Typ',
    'category': 'Kategoria',
    'notes': 'Notatki',
    'email': 'E-mail',
    'phone': 'Telefon',
    'address': 'Adres',
    'or': 'lub',
    'all': 'Wszystkie',
    
    // Dashboard
    'Active Customers': 'Aktywni klienci',
    'Completed Orders': 'Zrealizowane zamówienia',
    'Gross Profit': 'Zysk brutto',
    'Low Stock': 'Niski stan',
    'Net Profit': 'Zysk netto',
    'New Customers': 'Nowi klienci',
    'Out of Stock': 'Brak w magazynie',
    'Pending Orders': 'Oczekujące zamówienia',
    'Total Customers': 'Wszyscy klienci',
    'Total Expenses': 'Wszystkie wydatki',
    'Total Orders': 'Wszystkie zamówienia',
    'Total Products': 'Wszystkie produkty',
    'Total Revenue': 'Całkowity przychód',
    'Total Suppliers': 'Wszyscy dostawcy',
  },
  
  // Romanian (RO)
  ro: {
    'save': 'Salvează',
    'cancel': 'Anulează',
    'delete': 'Șterge',
    'edit': 'Editează',
    'add': 'Adaugă',
    'create': 'Creează',
    'update': 'Actualizează',
    'search': 'Caută',
    'filter': 'Filtrează',
    'export': 'Exportă',
    'import': 'Importă',
    'print': 'Tipărește',
    'download': 'Descarcă',
    'close': 'Închide',
    'back': 'Înapoi',
    'next': 'Următorul',
    'yes': 'Da',
    'no': 'Nu',
    'ok': 'OK',
    'loading': 'Se încarcă...',
    'error': 'Eroare',
    'success': 'Succes',
    'warning': 'Avertisment',
    'details': 'Detalii',
    'overview': 'Prezentare generală',
    'settings': 'Setări',
    'status': 'Stare',
    'active': 'Activ',
    'inactive': 'Inactiv',
    'pending': 'În așteptare',
    'completed': 'Finalizat',
    'name': 'Nume',
    'description': 'Descriere',
    'date': 'Data',
    'amount': 'Sumă',
    'total': 'Total',
    'balance': 'Sold',
    'price': 'Preț',
    'quantity': 'Cantitate',
    'type': 'Tip',
    'category': 'Categorie',
    'notes': 'Note',
    'email': 'E-mail',
    'phone': 'Telefon',
    'address': 'Adresă',
    'or': 'sau',
    'all': 'Toate',
    
    // Dashboard
    'Active Customers': 'Clienți activi',
    'Completed Orders': 'Comenzi finalizate',
    'Gross Profit': 'Profit brut',
    'Low Stock': 'Stoc redus',
    'Net Profit': 'Profit net',
    'New Customers': 'Clienți noi',
    'Out of Stock': 'Stoc epuizat',
    'Pending Orders': 'Comenzi în așteptare',
    'Total Customers': 'Total clienți',
    'Total Expenses': 'Total cheltuieli',
    'Total Orders': 'Total comenzi',
    'Total Products': 'Total produse',
    'Total Revenue': 'Venituri totale',
    'Total Suppliers': 'Total furnizori',
  }
};

// Process each language file
function processLanguage(lang) {
  if (!translations[lang]) return;
  
  const filePath = path.join(LOCALES_DIR, `${lang}.json`);
  let content = fs.readFileSync(filePath, 'utf8');
  
  const langMap = translations[lang];
  const prefix = `[${lang.toUpperCase()}] `;
  
  // Replace placeholders
  for (const [key, value] of Object.entries(langMap)) {
    const placeholder = prefix + key;
    const regex = new RegExp(`"\\[${lang.toUpperCase()}\\] ${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'g');
    content = content.replace(regex, `"${value}"`);
  }
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`✅ ${lang.toUpperCase()} processed`);
}

// Main
console.log('🌍 Processing translations...\n');

for (const lang of Object.keys(translations)) {
  processLanguage(lang);
}

console.log('\n✅ All translations processed!');
console.log('Run `npm run sync:translations` to verify.');
